force-app/main/default/objects/FeatureGate__mdt/FeatureGate__mdt.object-meta.xml
<CustomObject>
    <description>Metadata to control behaviour of certain product features.</description>
    <label>Feature Gate</label>
    <pluralLabel>Feature Gates</pluralLabel>
</CustomObject>

force-app/main/default/objects/FeatureGate__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Feature Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceParticipant__c/ServiceParticipant__c.object-meta.xml
<CustomObject>
    <label>Service Participant</label>
    <nameField>
        <label>Service Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceParticipant__c/fields/ServiceSchedule__c.field-meta.xml
<CustomField>
    <fullName>ServiceSchedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Schedule</label>
    <referenceTo>ServiceSchedule__c</referenceTo>
    <relationshipLabel>Service Participants</relationshipLabel>
    <relationshipName>Service_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceParticipant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waitlisted</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <default>true</default>
                <label>Enrolled</label>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/ServiceSchedule__c.object-meta.xml
<CustomObject>
    <label>Service Schedule</label>
    <nameField>
        <label>Service Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceSchedule__c/fields/ParticipantsEnrolled__c.field-meta.xml
<CustomField>
    <fullName>ParticipantsEnrolled__c</fullName>
    <inlineHelpText>The total number of Service Participants with Status set to Enrolled linked to this Service Schedule</inlineHelpText>
    <label>Participants Enrolled</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ServiceParticipantRollupsService.cls
/*
 *
 *  * Copyright (c) 2022, salesforce.com, inc.
 *  * All rights reserved.
 *  * SPDX-License-Identifier: BSD-3-Clause
 *  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 */
public with sharing class ServiceParticipantRollupsService {
    private static String ENROLLED = 'Enrolled';
    private static Set<String> FEATUREGATE_NAME = new Set<String>{
        'ServiceParticipantsToServiceSchedule'
    };

    public void processInsertedParticipants(List<ServiceParticipant__c> participants) {
        Integer participantCount;
        Set<Id> serviceScheduleIds = new Set<Id>();
        List<ServiceSchedule__c> serviceSchedulesToUpdate = new List<ServiceSchedule__c>();
        Map<Id, ServiceSchedule__c> schedules = new Map<Id, ServiceSchedule__c>();
        Boolean isfeatureGateActive = getFeatureGateStatus();

        if (isfeatureGateActive) {
            for (ServiceParticipant__c participant : participants) {
                serviceScheduleIds.add(participant.ServiceSchedule__c);
            }

            schedules = getServiceSchedules(serviceScheduleIds);

            for (ServiceSchedule__c schedule : schedules.values()) {
                participantCount = 0;
                for (
                    ServiceParticipant__c serviceParticipant : schedule.ServiceParticipants__r
                ) {
                    if (serviceParticipant.Status__c != ENROLLED) {
                        continue;
                    }
                    participantCount++;
                }
                schedule.ParticipantsEnrolled__c = participantCount;
                serviceSchedulesToUpdate.add(schedule);
            }

            if (!serviceSchedulesToUpdate.isEmpty()) {
                update serviceSchedulesToUpdate;
            }
        }
    }

    private Map<Id, ServiceSchedule__c> getServiceSchedules(Set<Id> scheduleIds) {
        return new Map<Id, ServiceSchedule__c>(
            [
                SELECT
                    Id,
                    ParticipantsEnrolled__c,
                    (SELECT Id, Status__c FROM ServiceParticipants__r)
                FROM ServiceSchedule__c
                WHERE Id IN :scheduleIds
            ]
        );
    }

    private Boolean getFeatureGateStatus() {
        List<FeatureGate__mdt> features = CustomMetadataSelector.getInstance()
            .getAllFeatureGates();

        for (FeatureGate__mdt feature : features) {
            if (feature.IsActive__c && FEATUREGATE_NAME.contains(feature.DeveloperName)) {
                return feature.IsActive__c;
            }
        }

        return false;
    }
}