force-app/main/default/objects/ProgramCohort__c/ProgramCohort__c.object-meta.xml
<CustomObject>
    <label>Program Cohort</label>
    <nameField>
        <label>Program Cohort</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramEngagement__c/ProgramEngagement__c.object-meta.xml
<CustomObject>
    <label>Program Engagement</label>
    <nameField>
        <label>Program Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramEngagement__c/fields/ProgramCohort__c.field-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomField>
    <fullName>ProgramCohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Cohort</label>
    <referenceTo>ProgramCohort__c</referenceTo>
    <relationshipLabel>Program Engagements</relationshipLabel>
    <relationshipName>ProgramEngagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SelectParticipantController.cls
public with sharing class SelectParticipantController {
    @TestVisible
    private static SelectParticipantService selectParticipantService = new SelectParticipantService();

    @AuraEnabled
    public static List<ProgramEngagement__c> getProgramEngagementsByServiceId(
        Id serviceId
    ) {
        try {
            return selectParticipantService.getProgramEngagementsByServiceId(serviceId);
        } catch (Exception e) {
            throw Util.getAuraHandledException(e);
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<ProgramCohort__c> getProgramCohorts(Id serviceId) {
        try {
            return selectParticipantService.getProgramCohorts(serviceId);
        } catch (Exception e) {
            throw Util.getAuraHandledException(e);
        }
    }

    @AuraEnabled(cacheable=true)
    public static selectParticipantService.InitialDataAndSetup getData(Id serviceId) {
        try {
            return selectParticipantService.getInitialDataSetupInfo(serviceId);
        } catch (Exception e) {
            throw Util.getAuraHandledException(e);
        }
    }

    @AuraEnabled
    public static List<ProgramEngagement__c> getFilteredProgramEnagagement(
        String searchValue
    ) {
        try {
            return selectParticipantService.getFilteredProgramEnagagement(searchValue);
        } catch (Exception e) {
            throw Util.getAuraHandledException(e);
        }
    }
}