force-app/main/default/objects/Bucket__mdt/Bucket__mdt.object-meta.xml
<CustomObject>
    <description>The logical grouping of a Bucketed Field, similar to &quot;Open&quot; and &quot;Closed&quot; in the case of Case.Status.</description>
    <label>Bucket</label>
    <pluralLabel>Buckets</pluralLabel>
</CustomObject>

force-app/main/default/objects/BucketedValue__mdt/BucketedValue__mdt.object-meta.xml
<CustomObject>
    <description>A value that should be bucketed, such as the Case.Status value &quot;New&quot; being bucketed into &quot;Open&quot;.</description>
    <label>Bucketed Value</label>
    <pluralLabel>Bucketed Values</pluralLabel>
</CustomObject>

force-app/main/default/objects/BucketedValue__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <inlineHelpText>The exact value that should be bucketed. If the field is a picklist, this should be the picklist value&apos;s API value.</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceSession__c/ServiceSession__c.object-meta.xml
<CustomObject>
    <label>Service Session</label>
    <nameField>
        <label>Service Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceSession__c/fields/SessionStart__c.field-meta.xml
<CustomField>
    <fullName>SessionStart__c</fullName>
    <label>Session Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceSession__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ServiceSessionService.cls
/*
 *
 *  * Copyright (c) 2020, salesforce.com, inc.
 *  * All rights reserved.
 *  * SPDX-License-Identifier: BSD-3-Clause
 *  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 */

public with sharing class ServiceSessionService {
    @TestVisible
    private ServiceSessionSelector serviceSessionSelector = new ServiceSessionSelector();

    @TestVisible
    private FieldBucketSelector bucketSelector = new FieldBucketSelector();

    public Map<String, List<ServiceSession__c>> getServiceSessionsByStartDate(
        String dateLiteral
    ) {
        Map<String, List<ServiceSession__c>> serviceSessions = new Map<String, List<ServiceSession__c>>();

        for (
            ServiceSession__c session : serviceSessionSelector.getServiceSessionsByStartDate(
                dateLiteral
            )
        ) {
            List<ServiceSession__c> sessions = new List<ServiceSession__c>();
            String sessionStartDate = session.SessionStart__c.format('EEEE, dd MMMM');

            if (serviceSessions.get(sessionStartDate) == null) {
                serviceSessions.put(sessionStartDate, new List<ServiceSession__c>());
            }

            if (serviceSessions.get(sessionStartDate) != null) {
                if (serviceSessions.containsKey(sessionStartDate)) {
                    sessions.add(session);
                    serviceSessions.get(sessionStartDate).addAll(sessions);
                }
            }
        }

        return serviceSessions;
    }

    public Set<String> getServiceSessionStatusBuckets(String serviceSessionStatus) {
        List<String> bucketNames = new List<String>{ serviceSessionStatus };
        Set<String> statuses = new Set<String>();

        Schema.SObjectType serviceSessionSObjType = ServiceSession__c.SObjectType;
        Schema.SObjectField serviceSessionStatusField = ServiceSession__c.Status__c;

        for (
            Bucket__mdt bucket : bucketSelector.getBuckets(
                bucketNames,
                serviceSessionSObjType,
                serviceSessionStatusField
            )
        ) {
            for (BucketedValue__mdt value : bucket.BucketedValues__r) {
                statuses.add(value.Value__c);
            }
        }

        return statuses;
    }
}