force-app/main/default/objects/Bucket__mdt/Bucket__mdt.object-meta.xml
<CustomObject>
    <description>The logical grouping of a Bucketed Field, similar to &quot;Open&quot; and &quot;Closed&quot; in the case of Case.Status.</description>
    <label>Bucket</label>
    <pluralLabel>Buckets</pluralLabel>
</CustomObject>

force-app/main/default/objects/ServiceDelivery__c/ServiceDelivery__c.object-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomObject>
    <label>Service Delivery</label>
    <nameField>
        <label>Service Delivery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceDelivery__c/fields/AttendanceStatus__c.field-meta.xml
<CustomField>
    <fullName>AttendanceStatus__c</fullName>
    <label>Attendance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Present</fullName>
            </value>
            <value>
                <fullName>Unexcused Absence</fullName>
            </value>
            <value>
                <fullName>Excused Absence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FieldBucketSelector_TEST.cls
/*
 *
 *  * Copyright (c) 2022, salesforce.com, inc.
 *  * All rights reserved.
 *  * SPDX-License-Identifier: BSD-3-Clause
 *  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 */

@IsTest
public with sharing class FieldBucketSelector_TEST {
    private static FieldBucketSelector bucketSelector = new FieldBucketSelector();

    @IsTest
    private static void getAttendanceBucketsReturnsPackagedBuckets() {
        List<String> bucketNames = new List<String>{ 'Absent', 'Present' };

        Schema.SObjectType serviceDeliverySObjType = ServiceDelivery__c.SObjectType;
        Schema.SObjectField statusField = ServiceDelivery__c.AttendanceStatus__c;

        List<Bucket__mdt> buckets = bucketSelector.getBuckets(
            bucketNames,
            serviceDeliverySObjType,
            statusField
        );

        System.assertEquals(
            2,
            buckets.size(),
            'Expected the 2 packaged attendance records to be returned.'
        );
        System.assertEquals(
            bucketNames[0],
            buckets[0].DeveloperName,
            'Expected the Absent bucket to be returned first.'
        );
        System.assertEquals(
            bucketNames[1],
            buckets[1].DeveloperName,
            'Expected the Present bucket to be returned second.'
        );
    }
}