force-app/main/default/objects/Bucket__mdt/Bucket__mdt.object-meta.xml
<CustomObject>
    <description>The logical grouping of a Bucketed Field, similar to &quot;Open&quot; and &quot;Closed&quot; in the case of Case.Status.</description>
    <label>Bucket</label>
    <pluralLabel>Buckets</pluralLabel>
</CustomObject>

force-app/main/default/objects/Bucket__mdt/fields/BucketedField__c.field-meta.xml
<CustomField>
    <fullName>BucketedField__c</fullName>
    <inlineHelpText>Which Bucketed Field does this Bucket belong to?</inlineHelpText>
    <label>Bucketed Field</label>
    <referenceTo>BucketedField__mdt</referenceTo>
    <relationshipLabel>Buckets</relationshipLabel>
    <relationshipName>Buckets</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/BucketedField__mdt/BucketedField__mdt.object-meta.xml
<CustomObject>
    <description>Field whose values can be bucketed into logical groupings, similar to Case.Status values have &quot;Open&quot; and &quot;Closed&quot; groupings.</description>
    <label>Bucketed Field</label>
    <pluralLabel>Bucketed Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/BucketedField__mdt/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <metadataRelationshipControllingField>BucketedField__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Bucketed_Fields</relationshipLabel>
    <relationshipName>Bucketed_Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/BucketedField__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Bucketed_Fields</relationshipLabel>
    <relationshipName>Bucketed_Fields</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/FieldBucketSelector.cls
/*
 *
 *  * Copyright (c) 2022, salesforce.com, inc.
 *  * All rights reserved.
 *  * SPDX-License-Identifier: BSD-3-Clause
 *  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 */

public with sharing class FieldBucketSelector {

    public List<Bucket__mdt> getBuckets(List<String> bucketNames) {
        // Note: there doesn't seem to be a way to get the subquery with .getAll() so I think we're stuck
        // with SOQL for this layer.
        return [
            SELECT
                Id,
                DeveloperName,
                BucketedField__r.Field__r.QualifiedApiName,
                BucketedField__r.Object__r.QualifiedApiName,
                QualifiedApiName,
                (SELECT Id, Value__c FROM BucketedValues__r)
            FROM Bucket__mdt
            WHERE DeveloperName IN :bucketNames AND NamespacePrefix = :Util.getNamespace()
            ORDER BY QualifiedApiName
        ];
    }

    public List<Bucket__mdt> getBuckets(List<String> bucketNames, Schema.SObjectType objectType, Schema.SObjectField bucketedField) {
        // Note: there doesn't seem to be a way to get the subquery with .getAll() so I think we're stuck
        // with SOQL for this layer.

        String sObjectAPIName = objectType.getDescribe().getName();
        String bucketedFieldAPIName = bucketedField.getDescribe().getLocalName();

        return [
            SELECT
            Id,
            DeveloperName,
            BucketedField__r.Field__r.QualifiedApiName,
            BucketedField__r.Object__r.QualifiedApiName,
            QualifiedApiName,
            (SELECT Id, Value__c FROM BucketedValues__r)
            FROM Bucket__mdt
            WHERE DeveloperName IN :bucketNames 
                AND NamespacePrefix = :Util.getNamespace()
                AND BucketedField__r.Object__r.QualifiedApiName = :sObjectAPIName
                //AND BucketedField__r.Field__r.QualifiedApiName = :bucketedFieldAPIName
            ORDER BY QualifiedApiName
        ];
    }    
}