force-app/main/default/objects/Bucket__mdt/Bucket__mdt.object-meta.xml
<CustomObject>
    <description>The logical grouping of a Bucketed Field, similar to &quot;Open&quot; and &quot;Closed&quot; in the case of Case.Status.</description>
    <label>Bucket</label>
    <pluralLabel>Buckets</pluralLabel>
</CustomObject>

force-app/main/default/objects/BucketedValue__mdt/BucketedValue__mdt.object-meta.xml
<CustomObject>
    <description>A value that should be bucketed, such as the Case.Status value &quot;New&quot; being bucketed into &quot;Open&quot;.</description>
    <label>Bucketed Value</label>
    <pluralLabel>Bucketed Values</pluralLabel>
</CustomObject>

force-app/main/default/objects/BucketedValue__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <inlineHelpText>The exact value that should be bucketed. If the field is a picklist, this should be the picklist value&apos;s API value.</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProgramEngagement__c/ProgramEngagement__c.object-meta.xml
<CustomObject>
    <label>Program Engagement</label>
    <nameField>
        <label>Program Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramEngagement__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>A Contact&#39;s stage in a Program Engagement. Picklist values are determined by your Admin. Don&#39;t delete or modify the API Name of the Active And Enrolled picklist values as they are referenced in PMM reports.</description>
    <inlineHelpText>These Picklist values describe a Contact&#39;s stage of engagement in a Program and are displayed in a Path. Values are determined by your Admin.</inlineHelpText>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Application Denied</fullName>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProgramEngagementService.cls
/*
 *
 *  * Copyright (c) 2022, salesforce.com, inc.
 *  * All rights reserved.
 *  * SPDX-License-Identifier: BSD-3-Clause
 *  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 */

public with sharing class ProgramEngagementService {
    @TestVisible
    private FieldBucketSelector bucketSelector = new FieldBucketSelector();

    @TestVisible
    private Set<String> activeStages {
        get {
            if (activeStages == null) {
                activeStages = getActiveStages();
            }
            return activeStages;
        }
        set;
    }

    public Set<String> getActiveStages() {
        List<String> bucketNames = new List<String>{ 'Active' };
        Set<String> activeStages = new Set<String>();

        Schema.SObjectType programEngagementSObjType = ProgramEngagement__c.SObjectType;
        Schema.SObjectField stageField = ProgramEngagement__c.Stage__c;

        for (
            Bucket__mdt bucket : bucketSelector.getBuckets(
                bucketNames,
                programEngagementSObjType,
                stageField
            )
        ) {
            for (BucketedValue__mdt value : bucket.BucketedValues__r) {
                activeStages.add(value.Value__c);
            }
        }

        return activeStages;
    }
}