force-app/main/default/objects/Bucket__mdt/Bucket__mdt.object-meta.xml
<CustomObject>
    <description>The logical grouping of a Bucketed Field, similar to &quot;Open&quot; and &quot;Closed&quot; in the case of Case.Status.</description>
    <label>Bucket</label>
    <pluralLabel>Buckets</pluralLabel>
</CustomObject>

force-app/main/default/objects/Bucket__mdt/fields/BucketedField__c.field-meta.xml
<CustomField>
    <fullName>BucketedField__c</fullName>
    <inlineHelpText>Which Bucketed Field does this Bucket belong to?</inlineHelpText>
    <label>Bucketed Field</label>
    <referenceTo>BucketedField__mdt</referenceTo>
    <relationshipLabel>Buckets</relationshipLabel>
    <relationshipName>Buckets</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/BucketedField__mdt/BucketedField__mdt.object-meta.xml
<CustomObject>
    <description>Field whose values can be bucketed into logical groupings, similar to Case.Status values have &quot;Open&quot; and &quot;Closed&quot; groupings.</description>
    <label>Bucketed Field</label>
    <pluralLabel>Bucketed Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/BucketedField__mdt/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <metadataRelationshipControllingField>BucketedField__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Bucketed_Fields</relationshipLabel>
    <relationshipName>Bucketed_Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/BucketedField__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Bucketed_Fields</relationshipLabel>
    <relationshipName>Bucketed_Fields</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/BucketedValue__mdt/BucketedValue__mdt.object-meta.xml
<CustomObject>
    <description>A value that should be bucketed, such as the Case.Status value &quot;New&quot; being bucketed into &quot;Open&quot;.</description>
    <label>Bucketed Value</label>
    <pluralLabel>Bucketed Values</pluralLabel>
</CustomObject>

force-app/main/default/objects/BucketedValue__mdt/fields/Bucket__c.field-meta.xml
<CustomField>
    <fullName>Bucket__c</fullName>
    <inlineHelpText>Which Bucket does this value belong to?</inlineHelpText>
    <label>Bucket</label>
    <referenceTo>Bucket__mdt</referenceTo>
    <relationshipLabel>Bucketed Values</relationshipLabel>
    <relationshipName>Bucketed_Values</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/BucketedValue__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <inlineHelpText>The exact value that should be bucketed. If the field is a picklist, this should be the picklist value&apos;s API value.</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FeatureGate__mdt/FeatureGate__mdt.object-meta.xml
<CustomObject>
    <description>Metadata to control behaviour of certain product features.</description>
    <label>Feature Gate</label>
    <pluralLabel>Feature Gates</pluralLabel>
</CustomObject>

force-app/main/default/objects/FeatureGate__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Feature Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestUtil.cls
/*
 *
 *  * Copyright (c) 2020, salesforce.com, inc.
 *  * All rights reserved.
 *  * SPDX-License-Identifier: BSD-3-Clause
 *  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 */

@IsTest
/**
 * Utility methods for test classes
 */
public with sharing class TestUtil {
    private static final Set<String> featureGateNames = new Set<String>{
        'ServiceDeliveriesToContact',
        'ServiceDeliveriesToService',
        'ServiceDeliveriesToServiceSession',
        'ServiceDeliveriesToProgramEngagement'
    };

    public static final String TEST_USER_EMAIL = 'temptestuser@caseplan.example.com';

    public static Integer counter {
        get {
            if (counter == null) {
                counter = 0;
            }
            counter++;

            return counter;
        }
        set;
    }

    public static Id mockId(SObjectType sObjType) {
        return mockIds(sObjType, 1)[0];
    }

    public static List<Id> mockIds(SObjectType sObjectType, Integer size) {
        String keyPrefix = sObjectType.getDescribe().getKeyPrefix();
        List<Id> ids = new List<Id>();

        for (Integer i = 0; i < size; i++) {
            Integer uniqueCounter = counter;
            ids.add(
                keyPrefix +
                '0'.repeat(12 - String.valueOf(uniqueCounter).length()) +
                uniqueCounter
            );
        }

        return ids;
    }

    public static User getTestUser() {
        // create user with no custom object permissions to test CRUD checks
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
        User user = new User(
            Alias = 'standt',
            Email = TEST_USER_EMAIL,
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = p.Id,
            TimeZoneSidKey = 'America/Chicago',
            UserName = TEST_USER_EMAIL
        );
        return user;
    }

    public static void turnOffFeatureGates(Set<String> developerNames) {
        // TestStub turned off Feature Gates so we can insert Service Deliveries without triggers running
        List<FeatureGate__mdt> featureGates = new List<FeatureGate__mdt>();
        for (String name : featureGateNames) {
            featureGates.add(
                new FeatureGate__mdt(
                    DeveloperName = name,
                    IsActive__c = !developerNames.contains(name)
                )
            );
        }

        TestStub customMetadataSelectorStub = new StubBuilder(
                CustomMetadataSelector.class
            )
            .when('getAllFeatureGates')
            .called()
            .thenReturn(featureGates)
            .build();

        CustomMetadataSelector.instance = (CustomMetadataSelector) customMetadataSelectorStub.create();
    }

    public static void turnOffFeatureGates() {
        turnOffFeatureGates(featureGateNames);
    }

    public class BucketedFieldBuilder extends RecordBuilder {
        public BucketedFieldBuilder() {
            super(BucketedField__mdt.SObjectType);
        }

        public BucketedFieldBuilder withDeveloperName(String developerName) {
            valuesByFieldName.put(
                String.valueOf(BucketedField__mdt.DeveloperName),
                developerName
            );
            return this;
        }

        public BucketedFieldBuilder withQualifiedApiName(String qualifiedApiName) {
            valuesByFieldName.put(
                String.valueOf(BucketedField__mdt.QualifiedApiName),
                qualifiedApiName
            );
            return this;
        }

        public BucketedFieldBuilder withField(String fieldApiName) {
            valuesByFieldName.put(
                String.valueOf(BucketedField__mdt.Field__c),
                fieldApiName
            );
            return this;
        }

        public BucketedFieldBuilder withObject(String objectApiName) {
            valuesByFieldName.put(
                String.valueOf(BucketedField__mdt.Object__c),
                objectApiName
            );
            return this;
        }
    }

    public class BucketedValueBuilder extends RecordBuilder {
        public BucketedValueBuilder() {
            super(BucketedValue__mdt.SObjectType);
        }

        public BucketedValueBuilder withDeveloperName(String developerName) {
            valuesByFieldName.put(
                String.valueOf(BucketedValue__mdt.DeveloperName),
                developerName
            );
            return this;
        }

        public BucketedValueBuilder withQualifiedApiName(String qualifiedApiName) {
            valuesByFieldName.put(
                String.valueOf(BucketedValue__mdt.QualifiedApiName),
                qualifiedApiName
            );
            return this;
        }

        public BucketedValueBuilder withBucket(String bucketName) {
            valuesByFieldName.put(
                String.valueOf(BucketedValue__mdt.Bucket__c),
                bucketName
            );
            return this;
        }

        public BucketedValueBuilder withValue(String value) {
            valuesByFieldName.put(String.valueOf(BucketedValue__mdt.Value__c), value);
            return this;
        }
    }

    public class BucketBuilder extends RecordBuilder {
        public BucketBuilder() {
            super(Bucket__mdt.SObjectType);
        }

        public BucketBuilder withDeveloperName(String developerName) {
            valuesByFieldName.put(
                String.valueOf(Bucket__mdt.DeveloperName),
                developerName
            );
            return this;
        }

        public BucketBuilder withQualifiedApiName(String qualifiedApiName) {
            valuesByFieldName.put(
                String.valueOf(Bucket__mdt.QualifiedApiName),
                qualifiedApiName
            );
            return this;
        }

        public BucketBuilder withBucketedField(BucketedField__mdt bucketedFieldRecord) {
            valuesByFieldName.put(
                Bucket__mdt.BucketedField__c.getDescribe().getRelationshipName(),
                bucketedFieldRecord
            );
            return withBucketedField(bucketedFieldRecord.Id);
        }

        public BucketBuilder withBucketedField(Id bucketedFieldId) {
            valuesByFieldName.put(
                String.valueOf(Bucket__mdt.BucketedField__c),
                bucketedFieldId
            );
            return this;
        }

        public BucketBuilder withBucketedValues(List<BucketedValue__mdt> values) {
            valuesByFieldName.put(
                Util.prefixNamespace('BucketedValues__r'),
                makeRelatedList(values)
            );
            return this;
        }
    }

    public virtual class RecordBuilder {
        protected Map<String, Object> valuesByFieldName = new Map<String, Object>();
        private String sObjectTypeName;

        public RecordBuilder(SObjectType sObjectType) {
            sObjectTypeName = String.valueOf(sObjectType);
        }

        public virtual RecordBuilder withMockId() {
            valuesByFieldName.put('Id', mockId(Bucket__mdt.SObjectType));
            return this;
        }

        public virtual RecordBuilder withId(Id actionItemId) {
            valuesByFieldName.put('Id', actionItemId);
            return this;
        }

        public virtual RecordBuilder withName(String name) {
            valuesByFieldName.put('Name', name);
            return this;
        }

        public virtual SObject build() {
            valuesByFieldName.put(
                'attributes',
                new Map<String, Object>{ 'type' => sObjectTypeName }
            );
            String jsonString = JSON.serialize(valuesByFieldName);

            return (SObject) JSON.deserialize(jsonString, SObject.class);
        }

        protected Map<String, Object> makeRelatedList(List<SObject> childRecords) {
            Map<String, Object> relatedList = new Map<String, Object>();
            relatedList.put('records', childRecords);
            relatedList.put('totalSize', childRecords.size());
            relatedList.put('done', true);

            return relatedList;
        }
    }
}