force-app/main/default/objects/ServiceParticipant__c/ServiceParticipant__c.object-meta.xml
<CustomObject>
    <label>Service Participant</label>
    <nameField>
        <label>Service Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceParticipant__c/fields/ServiceSchedule__c.field-meta.xml
<CustomField>
    <fullName>ServiceSchedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Schedule</label>
    <referenceTo>ServiceSchedule__c</referenceTo>
    <relationshipLabel>Service Participants</relationshipLabel>
    <relationshipName>Service_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceParticipant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waitlisted</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <default>true</default>
                <label>Enrolled</label>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/ServiceSchedule__c.object-meta.xml
<CustomObject>
    <label>Service Schedule</label>
    <nameField>
        <label>Service Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceSchedule__c/fields/ParticipantsEnrolled__c.field-meta.xml
<CustomField>
    <fullName>ParticipantsEnrolled__c</fullName>
    <inlineHelpText>The total number of Service Participants with Status set to Enrolled linked to this Service Schedule</inlineHelpText>
    <label>Participants Enrolled</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ServiceParticipantRollupsService_TEST.cls
/*
 *
 *  * Copyright (c) 2022, salesforce.com, inc.
 *  * All rights reserved.
 *  * SPDX-License-Identifier: BSD-3-Clause
 *  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 */
@IsTest
public with sharing class ServiceParticipantRollupsService_TEST {
    private static ServiceParticipantRollupsService rollupService = new ServiceParticipantRollupsService();

    @TestSetup
    private static void createTestData() {
        // By turning off none, we turn on all
        TestUtil.turnOffFeatureGates(new Set<String>{});
        TestDataFactory.generateAttendanceData('Monthly');
    }

    @IsTest
    private static void shouldUpdateParticipantsEnrolled() {
        createTestData();
        Integer expectedEnrolledParticipants = 2;
        ServiceParticipantRollupsService rollupService = new ServiceParticipantRollupsService();

        List<ServiceSchedule__c> schedulesToReturn = new List<ServiceSchedule__c>(
            [
                SELECT
                    Id,
                    ParticipantsEnrolled__c,
                    (
                        SELECT Id, Status__c
                        FROM ServiceParticipants__r
                        WHERE status__c = 'Enrolled'
                    )
                FROM ServiceSchedule__c
                LIMIT 1
            ]
        );

        List<ServiceParticipant__c> participants = new List<ServiceParticipant__c>(
            [
                SELECT Id, Status__c, ServiceSchedule__c
                FROM ServiceParticipant__c
                WHERE ServiceSchedule__c = :schedulesToReturn[0].Id
            ]
        );

        TestStub serviceScheduleSelectorStub = new StubBuilder(
                ServiceScheduleSelector.class
            )
            .when('getSchedulesWithParticipants', Set<Id>.class)
            .calledWith(new Set<Id>{ schedulesToReturn[0].Id })
            .thenReturn(schedulesToReturn)
            .build();

        rollupService.scheduleSelector = (ServiceScheduleSelector) serviceScheduleSelectorStub.create();

        Test.startTest();
        rollupService.processParticipantRollups(participants);
        Test.stopTest();

        System.assertEquals(
            expectedEnrolledParticipants,
            schedulesToReturn[0].ParticipantsEnrolled__c,
            'Expected the number of enrolled participants to be the same as what is returned from the selector'
        );

        serviceScheduleSelectorStub.assertCalledAsExpected();
    }
}