force-app/main/default/objects/ServiceParticipant__c/ServiceParticipant__c.object-meta.xml
<CustomObject>
    <label>Service Participant</label>
    <nameField>
        <label>Service Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceParticipant__c/fields/ServiceSchedule__c.field-meta.xml
<CustomField>
    <fullName>ServiceSchedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Schedule</label>
    <referenceTo>ServiceSchedule__c</referenceTo>
    <relationshipLabel>Service Participants</relationshipLabel>
    <relationshipName>Service_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/ServiceSchedule__c.object-meta.xml
<CustomObject>
    <label>Service Schedule</label>
    <nameField>
        <label>Service Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceSession__c/ServiceSession__c.object-meta.xml
<CustomObject>
    <label>Service Session</label>
    <nameField>
        <label>Service Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceSession__c/fields/ServiceSchedule__c.field-meta.xml
<CustomField>
    <fullName>ServiceSchedule__c</fullName>
    <label>Service Schedule</label>
    <referenceTo>ServiceSchedule__c</referenceTo>
    <relationshipLabel>Service Sessions</relationshipLabel>
    <relationshipName>Service_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ServiceScheduleModel.cls
public with sharing class ServiceScheduleModel {
    @AuraEnabled
    public ServiceSchedule__c serviceSchedule = new ServiceSchedule__c();
    @AuraEnabled
    public List<ServiceSession__c> serviceSessions = new List<ServiceSession__c>();
    @AuraEnabled
    public List<ServiceParticipant__c> serviceParticipants = new List<ServiceParticipant__c>();
    @AuraEnabled
    public Map<String, Map<String, String>> labels = new Map<String, Map<String, String>>();

    public ServiceScheduleModel() {
        this.labels.put('serviceSchedule', getServiceScheduleLabels());
        this.labels.put('serviceSession', getServiceSessionLabels());
        this.labels.put('serviceParticipant', getServiceParticipantLabels());
    }

    private static Map<String, String> serviceScheduleLabels = new Map<String, String>{
        'newServiceSchedule' => System.Label.New_Service_Schedule,
        'scheduleInformation' => System.Label.Service_Schedule_Information,
        'dateTime' => System.Label.Service_Schedule_Date_Time,
        'addToServiceSchedule' => String.format(
            System.Label.Add_To_Record,
            new List<String>{ ServiceSchedule__c.SObjectType.getDescribe().getLabel() }
        ),
        'reviewSchedule' => String.format(
            System.Label.Review_Records,
            new List<String>{ ServiceSession__c.SObjectType.getDescribe().getLabel() }
        )
    };

    private static Map<String, String> serviceSessionLabels = new Map<String, String>{
        'addSession' => String.format(
            System.Label.Add_Record,
            new List<String>{ ServiceSession__c.SObjectType.getDescribe().getLabel() }
        ),
        'reviewSessions' => String.format(
            System.Label.Review_Records,
            new List<String>{
                ServiceSession__c.SObjectType.getDescribe().getLabelPlural()
            }
        )
    };

    private static Map<String, String> serviceParticipantLabels = new Map<String, String>{
        'addServiceParticipants' => String.format(
            System.Label.Add_Record,
            new List<String>{
                ServiceParticipant__c.SObjectType.getDescribe().getLabelPlural()
            }
        )
    };

    private static Map<String, String> getServiceScheduleLabels() {
        serviceScheduleLabels.putAll(getObjectLabels(ServiceSchedule__c.sObjectType));

        return serviceScheduleLabels;
    }

    private static Map<String, String> getServiceSessionLabels() {
        serviceSessionLabels.putAll(getObjectLabels(ServiceSession__c.sObjectType));

        return serviceSessionLabels;
    }

    private static Map<String, String> getServiceParticipantLabels() {
        serviceParticipantLabels.putAll(
            getObjectLabels(ServiceParticipant__c.sObjectType)
        );

        return serviceParticipantLabels;
    }

    private static Map<String, String> getObjectLabels(SObjectType sObjectType) {
        return new Map<String, String>{
            'objectPluralLabel' => sObjectType.getDescribe().getLabelPlural(),
            'objectLabel' => sObjectType.getDescribe().getLabel(),
            'objectApiName' => sObjectType.getDescribe().getName()
        };
    }
}