force-app/main/default/objects/ServiceParticipant__c/ServiceParticipant__c.object-meta.xml
<CustomObject>
    <label>Service Participant</label>
    <nameField>
        <label>Service Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceParticipant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Participants</relationshipLabel>
    <relationshipName>ServiceParticipants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceParticipant__c/fields/ServiceSchedule__c.field-meta.xml
<CustomField>
    <fullName>ServiceSchedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Schedule</label>
    <referenceTo>ServiceSchedule__c</referenceTo>
    <relationshipLabel>Service Participants</relationshipLabel>
    <relationshipName>Service_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceParticipant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waitlisted</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <default>true</default>
                <label>Enrolled</label>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/ServiceSchedule__c.object-meta.xml
<CustomObject>
    <label>Service Schedule</label>
    <nameField>
        <label>Service Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceSchedule__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Campaign that this Service Schedule is linked to.</description>
    <inlineHelpText>The Campaign that this Service Schedule is linked to.</inlineHelpText>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Service Schedules</relationshipLabel>
    <relationshipName>ServiceSchedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ServiceParticipantService.cls
/*
 *
 *  * Copyright (c) 2021, salesforce.com, inc.
 *  * All rights reserved.
 *  * SPDX-License-Identifier: BSD-3-Clause
 *  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 */

public with sharing class ServiceParticipantService {
    @TestVisible
    private CampaignService campaignService = new CampaignService();

    public static Set<String> serviceParticipantStatuses = new Set<String>{
        'Waitlisted',
        'Enrolled',
        'Withdrawn'
    };

    public void addParticipantsToCampaign(List<ServiceParticipant__c> participants) {
        Map<Id, ServiceSchedule__c> serviceScheduleById = new Map<Id, ServiceSchedule__c>();

        Set<Id> linkedCampaignIds = new Set<Id>();
        Set<Id> participantContactIds = new Set<Id>();
        for (ServiceParticipant__c newServiceParticipant : participants) {
            serviceScheduleById.put(newServiceParticipant.ServiceSchedule__c, null);
            participantContactIds.add(newServiceParticipant.Contact__c);
        }

        serviceScheduleById = new Map<Id, ServiceSchedule__c>(
            [
                SELECT Id, Campaign__c
                FROM ServiceSchedule__c
                WHERE Id = :serviceScheduleById.keySet()
            ]
        );

        for (ServiceSchedule__c serviceSchedule : serviceScheduleById.values()) {
            if (serviceSchedule.Campaign__c != null) {
                linkedCampaignIds.add(serviceSchedule.Campaign__c);
            }
        }

        List<CampaignMember> preExistingCampaignMembers = [
            SELECT ContactId, CampaignId, Status
            FROM CampaignMember
            WHERE CampaignId = :linkedCampaignIds AND ContactId = :participantContactIds
        ];

        Map<String, CampaignMember> preExistingCampaignMembersByContactAndCampaignId = new Map<String, CampaignMember>();

        for (CampaignMember preExistingMember : preExistingCampaignMembers) {
            preExistingCampaignMEmbersByContactAndCampaignId.put(
                (String) preExistingMember.ContactId +
                (String) preExistingMember.CampaignId,
                preExistingMember
            );
        }

        for (ServiceSchedule__c serviceSchedule : serviceScheduleById.values()) {
            if (serviceSchedule.Campaign__c != null) {
                linkedCampaignIds.add(serviceSchedule.Campaign__c);
            }
        }

        for (ServiceParticipant__c newServiceParticipant : participants) {
            Id campaignId = serviceScheduleById.get(
                    newServiceParticipant.ServiceSchedule__c
                )
                .Campaign__c;
            if (campaignId == null || newServiceParticipant.Contact__c == null) {
                return;
            }

            String campaignMemberKey =
                (String) newServiceParticipant.Contact__c + (String) campaignId;
            if (
                preExistingCampaignMembersByContactAndCampaignId.containsKey(
                    campaignMemberKey
                )
            ) {
                CampaignMember preExistingMember = preExistingCampaignMembersByContactAndCampaignId.get(
                    campaignMemberKey
                );
                preExistingMember.Status = newServiceParticipant.Status__c;
                campaignService.addStagedCampaignMember(preExistingMember);
            } else {
                campaignService.stageCampaignMember(
                    newServiceParticipant.Contact__c,
                    serviceScheduleById.get(newServiceParticipant.ServiceSchedule__c)
                        .Campaign__c,
                    newServiceParticipant.Status__c
                );
            }
        }
        campaignService.commitCampaignMembers();
    }
}