force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceSchedule__c/ServiceSchedule__c.object-meta.xml
<CustomObject>
    <label>Service Schedule</label>
    <nameField>
        <label>Service Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceSchedule__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Campaign that this Service Schedule is linked to.</description>
    <inlineHelpText>The Campaign that this Service Schedule is linked to.</inlineHelpText>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Service Schedules</relationshipLabel>
    <relationshipName>ServiceSchedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Schedules</relationshipLabel>
    <relationshipName>Service_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ServiceScheduleTriggerHandler.cls
/*
 *
 *  * Copyright (c) 2021, salesforce.com, inc.
 *  * All rights reserved.
 *  * SPDX-License-Identifier: BSD-3-Clause
 *  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 */

public with sharing class ServiceScheduleTriggerHandler {
    @TestVisible
    private CampaignService campaignService = new CampaignService();

    private Set<String> serviceParticipantStatuses = new Set<String>{
        'Waitlisted',
        'Enrolled',
        'Withdrawn'
    };

    public void execute() {
        if (!Trigger.isExecuting) {
            return;
        }

        delegate();
    }

    @TestVisible
    private void delegate() {
        switch on Trigger.operationType {
            when BEFORE_INSERT {
                // TODO: bulkify, move to service class
                Map<Id, Service__c> serviceById = new Map<Id, Service__c>();
                for (
                    ServiceSchedule__c newServiceSchedule : (List<ServiceSchedule__c>) Trigger.new
                ) {
                    if (newServiceSchedule.Campaign__c == null) {
                        serviceById.put(newServiceSchedule.Service__c, null);
                    }
                }

                if (!serviceById.values().isEmpty()) {
                    serviceById = new Map<Id, Service__c>(
                        [SELECT Id, Name FROM Service__c WHERE Id = :serviceById.keySet()]
                    );
                }

                for (
                    ServiceSchedule__c newServiceSchedule : (List<ServiceSchedule__c>) Trigger.new
                ) {
                    if (newServiceSchedule.Campaign__c != null) {
                        continue;
                    }
                    String linkedCampaignName =
                        serviceById.get(newServiceSchedule.Service__c).Name +
                        ': ' +
                        newServiceSchedule.Name;
                    Campaign linkedCampaign = campaignService.createCampaign(
                        linkedCampaignName,
                        serviceParticipantStatuses
                    );
                    newServiceSchedule.Campaign__c = linkedCampaign.Id;
                }
            }
            when BEFORE_UPDATE {
                // TODO: bulkify, move to service class
                Map<Id, Service__c> serviceById = new Map<Id, Service__c>();
                for (
                    ServiceSchedule__c newServiceSchedule : (List<ServiceSchedule__c>) Trigger.new
                ) {
                    if (newServiceSchedule.Campaign__c == null) {
                        serviceById.put(newServiceSchedule.Service__c, null);
                    }
                }

                if (!serviceById.values().isEmpty()) {
                    serviceById = new Map<Id, Service__c>(
                        [SELECT Id, Name FROM Service__c WHERE Id = :serviceById.keySet()]
                    );
                }

                for (
                    ServiceSchedule__c newServiceSchedule : (List<ServiceSchedule__c>) Trigger.new
                ) {
                    if (newServiceSchedule.Campaign__c != null) {
                        continue;
                    }
                    String linkedCampaignName =
                        serviceById.get(newServiceSchedule.Service__c).Name +
                        ': ' +
                        newServiceSchedule.Name;
                    Campaign linkedCampaign = campaignService.createCampaign(
                        linkedCampaignName,
                        serviceParticipantStatuses
                    );
                    newServiceSchedule.Campaign__c = linkedCampaign.Id;
                }
            }
            when AFTER_DELETE {
            }
            when AFTER_INSERT {
            }
            when AFTER_UNDELETE {
            }
            when AFTER_UPDATE {
            }
            when else {
                return;
            }
        }
    }
}