force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/NumAbsentServiceDeliveries__c.field-meta.xml
<CustomField>
    <fullName>NumAbsentServiceDeliveries__c</fullName>
    <label>Number of Absent Service Deliveries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/ServiceDelivery__c.object-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomObject>
    <label>Service Delivery</label>
    <nameField>
        <label>Service Delivery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceDelivery__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Deliveries</relationshipLabel>
    <relationshipName>ServiceDeliveries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ServiceRollupsSchedulable.cls
/*
 *
 *  * Copyright (c) 2021, salesforce.com, inc.
 *  * All rights reserved.
 *  * SPDX-License-Identifier: BSD-3-Clause
 *  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 */

public class ServiceRollupsSchedulable implements Database.Batchable<SObject>, Schedulable {
    @TestVisible
    private QueryBuilder queryBuilder = new QueryBuilder();
    @TestVisible
    private Set<Id> serviceIds = new Set<Id>();

    public void execute(SchedulableContext context) {
        Database.executeBatch(new ServiceRollupsSchedulable(), 2000);
    }

    public Database.Querylocator start(Database.BatchableContext bc) {
        String query = serviceWithRollupDataQuery();
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Service__c> services) {
        for (Service__c serviceRecord : services) {
            serviceIds.add(serviceRecord.Id);
        }
    }

    public void finish(Database.BatchableContext bc) {
        Database.executeBatch(
            new ServiceDeliveryRollupsBatch(
                Service__c.SObjectType,
                ServiceDelivery__c.Service__c,
                serviceIds
            ),
            2000
        );
    }

    private String serviceWithRollupDataQuery() {
        // Find services that have had previous rollups and send them to the service delivery
        // batch in order to null the field values when services no longer have rollup data.
        // For example: all service delivery records were reparented to a different service.
        // If the service has updated rollup values we expect the service delivery batch to update them.
        // When services do not have a change to rollup values we expect them not to be touched.
        queryBuilder.withSObjectType(Service__c.SObjectType)
            .withSelectFields(new List<String>{ String.valueOf(Service__c.Id) })
            .addCondition(
                String.valueOf(Service__c.NumPresentServiceDeliveries__c) +
                ' >= 0 OR ' +
                String.valueOf(Service__c.NumAbsentServiceDeliveries__c) +
                ' >= 0'
            );
        return queryBuilder.buildSoqlQuery();
    }
}