force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceDelivery__c/ServiceDelivery__c.object-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomObject>
    <label>Service Delivery</label>
    <nameField>
        <label>Service Delivery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceDelivery__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Deliveries</relationshipLabel>
    <relationshipName>ServiceDeliveries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ServiceDeliveryTriggerHandler_TEST.cls
@IsTest
public with sharing class ServiceDeliveryTriggerHandler_TEST {
    @TestSetup
    private static void makeData() {
        TestDataFactory.generateServiceData();
    }

    private ServiceDelivery__c getServiceDelivery() {
        Service__c service = [SELECT Id FROM Service__c LIMIT 1];
        return new ServiceDelivery__c(Name = 'test', Service__c = service.Id);
    }

    @IsTest
    private static void testExecuteFromNonTrigger() {
        new ServiceDeliveryTriggerHandler().execute();
    }

    @IsTest
    private static void testDML() {
        // Note: strictly line coverage here since nothing is happening yet to Assert
        ServiceDelivery__c sd = getServiceDelivery();
        insert sd;
        update sd;
        delete sd;
        undelete sd;
    }
}