force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceDelivery__c/ServiceDelivery__c.object-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomObject>
    <label>Service Delivery</label>
    <nameField>
        <label>Service Delivery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceDelivery__c/fields/AttendanceStatus__c.field-meta.xml
<CustomField>
    <fullName>AttendanceStatus__c</fullName>
    <label>Attendance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Present</fullName>
            </value>
            <value>
                <fullName>Unexcused Absence</fullName>
            </value>
            <value>
                <fullName>Excused Absence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Deliveries</relationshipLabel>
    <relationshipName>ServiceDeliveries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AttendanceSystemAccess_TEST.cls
@IsTest
public with sharing class AttendanceSystemAccess_TEST {
    private static AttendanceSystemAccess systemAccess = new AttendanceSystemAccess();
    private static Service__c serviceRecord;
    private static final String PRESENT_STATUS = 'Present';

    @TestSetup
    private static void setupServiceSessionData() {
        TestDataFactory.generateAttendanceData('Monthly');

        serviceRecord = [SELECT Id FROM Service__c LIMIT 1];

        insert new ServiceDelivery__c(
            Name = 'test',
            Service__c = serviceRecord.Id,
            AttendanceStatus__c = PRESENT_STATUS
        );
    }

    @IsTest
    private static void shouldGetAllRecordsForStandardUser() {
        serviceRecord = [SELECT Id FROM Service__c LIMIT 1];

        User standardUser = TestUtil.getTestUser();
        List<ServiceDelivery__c> recordsWithAccess;

        System.runAs(standardUser) {
            recordsWithAccess = systemAccess.getAttendanceRecords(
                ServiceDelivery__c.Service__c,
                new Set<Id>{ serviceRecord.Id },
                new List<String>{ PRESENT_STATUS }
            );
        }

        System.assertEquals(
            1,
            recordsWithAccess.size(),
            'Expected the user to be able to bypass sharing.'
        );
    }

    @IsTest
    private static void shouldUpdateUnsharedRecordByStandardUser() {
        String updatedName = 'Services R Us';
        serviceRecord = [SELECT Id, Name FROM Service__c LIMIT 1];
        System.assertNotEquals(
            updatedName,
            serviceRecord.Name,
            'The service record name was not as expected.'
        );
        serviceRecord.Name = updatedName;

        User standardUser = TestUtil.getTestUser();

        System.runAs(standardUser) {
            systemAccess.updateRecords(new List<SObject>{ serviceRecord });
        }

        serviceRecord = [SELECT Id, Name FROM Service__c LIMIT 1];
        System.assertEquals(
            updatedName,
            serviceRecord.Name,
            'The service record name was not as expected.'
        );
    }
}