force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceSchedule__c/ServiceSchedule__c.object-meta.xml
<CustomObject>
    <label>Service Schedule</label>
    <nameField>
        <label>Service Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceSchedule__c/fields/AllDay__c.field-meta.xml
<CustomField>
    <fullName>AllDay__c</fullName>
    <defaultValue>false</defaultValue>
    <label>All day</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/fields/CreateServiceSessionRecords__c.field-meta.xml
<CustomField>
    <fullName>CreateServiceSessionRecords__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>When selected, Service Session records will be automatically created.</inlineHelpText>
    <label>Create Service Session</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/fields/DaysOfWeek__c.field-meta.xml
<CustomField>
    <fullName>DaysOfWeek__c</fullName>
    <label>Days of the Week</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Sun</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Mon</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Tue</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Wed</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Thu</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Fri</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Sat</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/fields/DefaultServiceQuantity__c.field-meta.xml
<CustomField>
    <fullName>DefaultServiceQuantity__c</fullName>
    <description>The default Service quantity reflected on a Service Delivery when tracking attendance.</description>
    <inlineHelpText>The default Service quantity reflected on a Service Delivery when tracking attendance.</inlineHelpText>
    <label>Default Service Quantity</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/fields/FirstSessionEnd__c.field-meta.xml
<CustomField>
    <fullName>FirstSessionEnd__c</fullName>
    <label>First Session End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/fields/FirstSessionStart__c.field-meta.xml
<CustomField>
    <fullName>FirstSessionStart__c</fullName>
    <defaultValue>NOW() + ((30 - MOD( Minute( ( TIMEVALUE( NOW() ) ) ), 30 )) / 60)/24</defaultValue>
    <label>First Session Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>One Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/fields/Interval__c.field-meta.xml
<CustomField>
    <fullName>Interval__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>The interval between sessions. For a weekly schedule, an interval of 2 means once every 2 weeks.</inlineHelpText>
    <label>Interval</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/fields/MonthlyRecurrenceOption__c.field-meta.xml
<CustomField>
    <fullName>MonthlyRecurrenceOption__c</fullName>
    <label>Monthly Recurrence Option</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/fields/NumberOfServiceSessions__c.field-meta.xml
<CustomField>
    <fullName>NumberOfServiceSessions__c</fullName>
    <label>Number of Service Sessions</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/fields/OtherServiceProvider__c.field-meta.xml
<CustomField>
    <fullName>OtherServiceProvider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Other Service Provider</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Schedules (Other Service Provider)</relationshipLabel>
    <relationshipName>Service_Schedules1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/fields/ParticipantCapacity__c.field-meta.xml
<CustomField>
    <fullName>ParticipantCapacity__c</fullName>
    <label>Participant Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/fields/PrimaryServiceProvider__c.field-meta.xml
<CustomField>
    <fullName>PrimaryServiceProvider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Service Provider</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Schedules</relationshipLabel>
    <relationshipName>Service_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Schedules</relationshipLabel>
    <relationshipName>Service_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/fields/ServiceScheduleEndDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceScheduleEndDate__c</fullName>
    <label>Service Schedule End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/fields/ServiceScheduleEnds__c.field-meta.xml
<CustomField>
    <fullName>ServiceScheduleEnds__c</fullName>
    <label>Service Schedule Ends</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On</fullName>
            </value>
            <value>
                <fullName>After</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ServiceScheduleSelector.cls
/*
 *
 *  * Copyright (c) 2022, salesforce.com, inc.
 *  * All rights reserved.
 *  * SPDX-License-Identifier: BSD-3-Clause
 *  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 */

public with sharing class ServiceScheduleSelector {
    public ServiceSchedule__c getServiceScheduleById(Id serviceScheduleId) {
        List<ServiceSchedule__c> serviceSchedules = getServiceSchedulesById(
            new Set<Id>{ serviceScheduleId }
        );
        return serviceSchedules.size() > 0 ? serviceSchedules[0] : null;
    }

    public List<ServiceSchedule__c> getServiceSchedulesById(Set<Id> serviceScheduleIds) {
        List<ServiceSchedule__c> serviceSchedules = new List<ServiceSchedule__c>();

        if (Schema.SObjectType.ServiceSchedule__c.isAccessible()) {
            serviceSchedules = [
                SELECT
                    Id,
                    Name,
                    AllDay__c,
                    CreateServiceSessionRecords__c,
                    DaysOfWeek__c,
                    DefaultServiceQuantity__c,
                    FirstSessionEnd__c,
                    FirstSessionStart__c,
                    Frequency__c,
                    Interval__c,
                    MonthlyRecurrenceOption__c,
                    NumberOfServiceSessions__c,
                    OtherServiceProvider__c,
                    ParticipantCapacity__c,
                    PrimaryServiceProvider__c,
                    ServiceScheduleEndDate__c,
                    ServiceScheduleEnds__c,
                    Service__c
                FROM ServiceSchedule__c
                WHERE Id = :serviceScheduleIds
            ];
        }

        return Security.stripInaccessible(AccessType.READABLE, serviceSchedules)
            .getRecords();
    }
}