force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/NumAbsentServiceDeliveries__c.field-meta.xml
<CustomField>
    <fullName>NumAbsentServiceDeliveries__c</fullName>
    <label>Number of Absent Service Deliveries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/ServiceDelivery__c.object-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomObject>
    <label>Service Delivery</label>
    <nameField>
        <label>Service Delivery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceDelivery__c/fields/AttendanceStatus__c.field-meta.xml
<CustomField>
    <fullName>AttendanceStatus__c</fullName>
    <label>Attendance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Present</fullName>
            </value>
            <value>
                <fullName>Unexcused Absence</fullName>
            </value>
            <value>
                <fullName>Excused Absence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/Quantity__c.field-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomField>
    <fullName>Quantity__c</fullName>
    <description>A 2-decimal numeric field for Quantity of a Service Delivery expressed in the Unit of Measurement in the Service. For example, 30 minutes of tutoring where the Unit of Measure is hours, Quantity is .50.</description>
    <inlineHelpText>A 2-decimal numeric field for Quantity of a Service Delivery expressed in the Unit of Measurement in the Service. For example, 30 minutes of tutoring where the Unit of Measure is hours, Quantity is .50.</inlineHelpText>
    <label>Quantity</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Deliveries</relationshipLabel>
    <relationshipName>ServiceDeliveries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SystemAccess_TEST.cls
/*
 *
 *  * Copyright (c) 2021, salesforce.com, inc.
 *  * All rights reserved.
 *  * SPDX-License-Identifier: BSD-3-Clause
 *  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 */

@IsTest
public with sharing class SystemAccess_TEST {
    private static SystemAccess systemAccess = new SystemAccess();
    private static Service__c serviceRecord;
    private static final String PRESENT_STATUS = 'Present';
    private static final String ABSENT_STATUS = 'UnExcused Absence';
    private static final String PRESENT_FIELD = 'NumPresentServiceDeliveries__c';
    private static final String ABSENT_FIELD = 'NumAbsentServiceDeliveries__c';

    @TestSetup
    private static void setupServiceSessionData() {
        TestUtil.turnOffFeatureGates();
        TestDataFactory.generateAttendanceData('Monthly');

        serviceRecord = [SELECT Id FROM Service__c LIMIT 1];

        List<ServiceDelivery__c> serviceDeliveries = new List<ServiceDelivery__c>();
        serviceDeliveries.add(
            new ServiceDelivery__c(
                Name = 'test',
                Service__c = serviceRecord.Id,
                Quantity__c = 10,
                AttendanceStatus__c = PRESENT_STATUS
            )
        );

        serviceDeliveries.add(
            new ServiceDelivery__c(
                Name = 'test Absent',
                Service__c = serviceRecord.Id,
                Quantity__c = 0,
                AttendanceStatus__c = ABSENT_STATUS
            )
        );

        insert serviceDeliveries;
    }

    @IsTest
    private static void shouldGetAllDeliveryRollupRecordsForStandardUser() {
        serviceRecord = [SELECT Id FROM Service__c LIMIT 1];

        User standardUser = TestUtil.getTestUser();
        List<ServiceDelivery__c> recordsWithAccess;

        System.runAs(standardUser) {
            recordsWithAccess = systemAccess.getDeliveryRecordsToRollup(
                String.valueOf(ServiceDelivery__c.Service__c),
                new Set<Id>{ serviceRecord.Id }
            );
        }

        System.assertEquals(
            3,
            recordsWithAccess.size(),
            'Expected the user to be able to bypass sharing.'
        );
    }

    @IsTest
    private static void shouldGetAllDeliveryRollupsCountsForStandardUser() {
        serviceRecord = [SELECT Id FROM Service__c LIMIT 1];

        User standardUser = TestUtil.getTestUser();
        Integer rollupCount;

        System.runAs(standardUser) {
            rollupCount = systemAccess.getDeliveryRollupsCount(
                'Service__c',
                serviceRecord.Id
            );
        }

        System.assertEquals(
            3,
            rollupCount,
            'Expected the user to be able to bypass sharing.'
        );
    }

    @IsTest
    private static void shouldUpdateUnsharedRecordByStandardUser() {
        String updatedName = 'Services R Us';
        serviceRecord = [SELECT Id, Name FROM Service__c LIMIT 1];
        System.assertNotEquals(
            updatedName,
            serviceRecord.Name,
            'The service record name was not as expected.'
        );
        serviceRecord.Name = updatedName;

        User standardUser = TestUtil.getTestUser();

        System.runAs(standardUser) {
            systemAccess.updateRecords(new List<SObject>{ serviceRecord });
        }

        serviceRecord = [SELECT Id, Name FROM Service__c LIMIT 1];
        System.assertEquals(
            updatedName,
            serviceRecord.Name,
            'The service record name was not as expected.'
        );
    }

    @IsTest
    private static void shouldGetAllRecordIdsForStandardUser() {
        serviceRecord = [SELECT Id FROM Service__c LIMIT 1];

        User standardUser = TestUtil.getTestUser();
        List<sObject> recordsWithAccess;

        System.runAs(standardUser) {
            recordsWithAccess = systemAccess.getRecordsById(
                Service__c.sObjectType,
                new Set<Id>{ serviceRecord.Id },
                new List<String>{ PRESENT_FIELD, ABSENT_FIELD }
            );
        }

        System.assertEquals(
            1,
            recordsWithAccess.size(),
            'Expected the user to be able to bypass sharing.'
        );
    }

    @IsTest
    private static void shouldGetDeliveryRollupsQueryForStandardUser() {
        serviceRecord = [SELECT Id FROM Service__c LIMIT 1];

        User standardUser = TestUtil.getTestUser();
        String rollupQuery;

        System.runAs(standardUser) {
            rollupQuery = systemAccess.getDeliveryRollupsQuery('Service__c');
        }

        System.assertNotEquals(null, rollupQuery, 'Expected the query to be returned.');
    }
}