force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceDelivery__c/ServiceDelivery__c.object-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomObject>
    <label>Service Delivery</label>
    <nameField>
        <label>Service Delivery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceDelivery__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Deliveries</relationshipLabel>
    <relationshipName>Service_Deliveries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Deliveries</relationshipLabel>
    <relationshipName>ServiceDeliveries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/ServiceSchedule__c.field-meta.xml
<CustomField>
    <fullName>ServiceSchedule__c</fullName>
    <formula>ServiceSession__r.ServiceSchedule__c</formula>
    <label>Service Schedule</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/ServiceSession__c.field-meta.xml
<CustomField>
    <fullName>ServiceSession__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Session</label>
    <referenceTo>ServiceSession__c</referenceTo>
    <relationshipLabel>Service Deliveries</relationshipLabel>
    <relationshipName>Service_Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceParticipant__c/ServiceParticipant__c.object-meta.xml
<CustomObject>
    <label>Service Participant</label>
    <nameField>
        <label>Service Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceParticipant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Participants</relationshipLabel>
    <relationshipName>ServiceParticipants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceParticipant__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Participants</relationshipLabel>
    <relationshipName>ServiceParticipants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceParticipant__c/fields/ServiceSchedule__c.field-meta.xml
<CustomField>
    <fullName>ServiceSchedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Schedule</label>
    <referenceTo>ServiceSchedule__c</referenceTo>
    <relationshipLabel>Service Participants</relationshipLabel>
    <relationshipName>Service_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/ServiceSchedule__c.object-meta.xml
<CustomObject>
    <label>Service Schedule</label>
    <nameField>
        <label>Service Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceSchedule__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Schedules</relationshipLabel>
    <relationshipName>Service_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceSession__c/ServiceSession__c.object-meta.xml
<CustomObject>
    <label>Service Session</label>
    <nameField>
        <label>Service Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceSession__c/fields/ServiceSchedule__c.field-meta.xml
<CustomField>
    <fullName>ServiceSchedule__c</fullName>
    <label>Service Schedule</label>
    <referenceTo>ServiceSchedule__c</referenceTo>
    <relationshipLabel>Service Sessions</relationshipLabel>
    <relationshipName>Service_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AttendanceSelector_TEST.cls
@IsTest
public with sharing class AttendanceSelector_TEST {
    private static AttendanceSelector selector = new AttendanceSelector();

    @TestSetup
    private static void setupServiceSessionData() {
        TestDataFactory.generateAttendanceData();
    }

    @IsTest
    private static void getServiceDeliveriesFiltersWithClient() {
        List<ServiceDelivery__c> actualDeliveries;
        Id sessionId = [SELECT Id FROM ServiceSession__c LIMIT 1].Id;

        ServiceDelivery__c serviceDelivery = [
            SELECT Service__c, ServiceSession__c
            FROM ServiceDelivery__c
            WHERE ServiceSession__c = :sessionId
        ];
        serviceDelivery.Contact__c = null;
        insert serviceDelivery.clone();

        Test.startTest();
        actualDeliveries = selector.getServiceDeliveriesBySessionId(sessionId);
        Test.stopTest();

        List<ServiceDelivery__c> sessionDeliveries = [
            SELECT Id
            FROM ServiceDelivery__c
            WHERE ServiceSession__c = :sessionId
        ];
        System.assert(
            !actualDeliveries.isEmpty() &&
            sessionDeliveries.size() > actualDeliveries.size(),
            'Expected only sessions with contact ids to be returned, actualDeliveries: ' +
            actualDeliveries.size() +
            '; sessionDeliveries: ' +
            sessionDeliveries.size()
        );

        for (ServiceDelivery__c delivery : actualDeliveries) {
            System.assertNotEquals(
                null,
                delivery.Contact__c,
                'Expected only deliveries related to a client to be returned.'
            );
        }
    }

    @IsTest
    private static void getServiceParticipantsByScheduleIdShouldReturnAllWhenNoExistingContacts() {
        ServiceSession__c session = [
            SELECT Id, ServiceSchedule__c
            FROM ServiceSession__c
            LIMIT 1
        ];
        List<ServiceParticipant__c> participants = [
            SELECT Id, Contact__c
            FROM ServiceParticipant__c
            WHERE ServiceSchedule__c = :session.ServiceSchedule__c
        ];
        System.assert(
            participants.size() > 1,
            'Sanity check that at least 2 participants should be found.'
        );
        List<ServiceParticipant__c> actualParticipants = selector.getServiceParticipantsByScheduleId(
            session.ServiceSchedule__c,
            new Set<Id>()
        );

        System.assertEquals(
            participants.size(),
            actualParticipants.size(),
            'Expected all participant records to be returned.'
        );
    }

    @IsTest
    private static void getServiceParticipantsByScheduleIdShouldOmitExistingContacts() {
        ServiceSession__c session = [
            SELECT Id, ServiceSchedule__c
            FROM ServiceSession__c
            LIMIT 1
        ];
        List<ServiceParticipant__c> participants = [
            SELECT Id, Contact__c
            FROM ServiceParticipant__c
            WHERE ServiceSchedule__c = :session.ServiceSchedule__c
        ];
        System.assert(
            participants.size() > 1,
            'Sanity check that at least 2 participants should be found.'
        );
        List<ServiceParticipant__c> actualParticipants = selector.getServiceParticipantsByScheduleId(
            session.ServiceSchedule__c,
            new Set<Id>{ participants[0].Contact__c }
        );

        System.assertEquals(
            participants.size() - 1,
            actualParticipants.size(),
            'Expected one participant record to be excluded.'
        );
    }
}