force-app/main/default/objects/ServiceDelivery__c/ServiceDelivery__c.object-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomObject>
    <label>Service Delivery</label>
    <nameField>
        <label>Service Delivery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceDelivery__c/fields/AttendanceStatus__c.field-meta.xml
<CustomField>
    <fullName>AttendanceStatus__c</fullName>
    <label>Attendance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Present</fullName>
            </value>
            <value>
                <fullName>Unexcused Absence</fullName>
            </value>
            <value>
                <fullName>Excused Absence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/DeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDate__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Delivery Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/Quantity__c.field-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomField>
    <fullName>Quantity__c</fullName>
    <description>A 2-decimal numeric field for Quantity of a Service Delivery expressed in the Unit of Measurement in the Service. For example, 30 minutes of tutoring where the Unit of Measure is hours, Quantity is .50.</description>
    <inlineHelpText>A 2-decimal numeric field for Quantity of a Service Delivery expressed in the Unit of Measurement in the Service. For example, 30 minutes of tutoring where the Unit of Measure is hours, Quantity is .50.</inlineHelpText>
    <label>Quantity</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SystemAccess.cls
/*
 *
 *  * Copyright (c) 2021, salesforce.com, inc.
 *  * All rights reserved.
 *  * SPDX-License-Identifier: BSD-3-Clause
 *  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 */

/*
 * We must bypass sharing in order to rollup all detail records to the parent entity.
 */
public without sharing class SystemAccess {
    private QueryBuilder queryBuilder = new QueryBuilder();

    public String getDeliveryRollupsQuery(String lookupField) {
        return buildDeliveryRollupsQuery(lookupField, ' != null');
    }

    public Integer getDeliveryRollupsCount(String lookupField, Id recordId) {
        setDeliveryRollupQueryBuilder(lookupField, ' = :recordId');

        return Database.countQuery(queryBuilder.buildCountQuery());
    }

    public List<SObject> getParentsWithDeliveries(
        SObjectType sObjectType,
        String lookupField,
        List<SObject> records
    ) {
        // Find all records that have service delivery child records e.g.
        // SELECT Id FROM Contact where Id in (SELECT Contact FROM ServiceDelivery__c
        // WHERE Contact IN :records)
        String query = queryBuilder
            .reset()
            .withSObjectType(sObjectType)
            .withSelectFields(new List<String>{ 'Id' })
            .addCondition(
                'Id IN (SELECT ' +
                lookupField +
                ' FROM ' +
                String.valueOf(ServiceDelivery__c.SObjectType) +
                ' WHERE ' +
                lookupField +
                ' IN :records)'
            )
            .buildSoqlQuery();

        return Database.query(query);
    }

    public List<ServiceDelivery__c> getDeliveryRecordsToRollup(
        String lookupField,
        Set<Id> recordIds
    ) {
        String query = buildDeliveryRollupsQuery(
            String.valueOf(lookupField),
            ' IN: recordIds'
        );
        return Database.query(query);
    }

    public List<SObject> getRecordsById(
        sObjectType sObjectType,
        Set<Id> recordIds,
        List<String> selectFields
    ) {
        return Database.query(
            queryBuilder
                .reset()
                .withSObjectType(sObjectType)
                .withSelectFields(selectFields)
                .addCondition('Id IN :recordIds')
                .buildSoqlQuery()
        );
    }

    public void updateRecords(List<SObject> sObjects) {
        update sObjects;
    }

    private String buildDeliveryRollupsQuery(
        String lookupField,
        String lookupFieldCondition
    ) {
        setDeliveryRollupQueryBuilder(lookupField, lookupFieldCondition);
        queryBuilder
            .withSelectFields(
                new List<String>{
                    String.valueOf(ServiceDelivery__c.AttendanceStatus__c),
                    String.valueOf(ServiceDelivery__c.DeliveryDate__c),
                    String.valueOf(lookupField),
                    String.valueOf(ServiceDelivery__c.Quantity__c)
                }
            );

        return queryBuilder.buildSoqlQuery();
    }

    private QueryBuilder setDeliveryRollupQueryBuilder(
        String lookupField,
        String lookupFieldCondition
    ) {
        String condition = lookupField + lookupFieldCondition;

        queryBuilder
            .reset()
            .withSObjectType(ServiceDelivery__c.SObjectType)
            .addCondition(lookupField + lookupFieldCondition)
            .withOrderBy(
                lookupField +
                ', ' +
                String.valueOf(ServiceDelivery__c.DeliveryDate__c) +
                ' ASC '
            );

        return queryBuilder;
    }
}