force-app/main/default/objects/ServiceDelivery__c/ServiceDelivery__c.object-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomObject>
    <label>Service Delivery</label>
    <nameField>
        <label>Service Delivery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceDelivery__c/fields/AttendanceStatus__c.field-meta.xml
<CustomField>
    <fullName>AttendanceStatus__c</fullName>
    <label>Attendance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Present</fullName>
            </value>
            <value>
                <fullName>Unexcused Absence</fullName>
            </value>
            <value>
                <fullName>Excused Absence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/DeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDate__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Delivery Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/Quantity__c.field-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomField>
    <fullName>Quantity__c</fullName>
    <description>A 2-decimal numeric field for Quantity of a Service Delivery expressed in the Unit of Measurement in the Service. For example, 30 minutes of tutoring where the Unit of Measure is hours, Quantity is .50.</description>
    <inlineHelpText>A 2-decimal numeric field for Quantity of a Service Delivery expressed in the Unit of Measurement in the Service. For example, 30 minutes of tutoring where the Unit of Measure is hours, Quantity is .50.</inlineHelpText>
    <label>Quantity</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ServiceDelivery.cls
public with sharing class ServiceDelivery {
    private ServiceDelivery__c delivery;

    private static final String ABSENT = 'Absent';
    private static final String PRESENT = 'Present';
    private static List<String> BUCKET_NAMES = new List<String>{ ABSENT, PRESENT };

    private static Map<String, List<String>> statusBuckets = new ServiceDeliveryService()
        .getStatusBuckets(BUCKET_NAMES);
    private static List<String> presentStatuses = statusBuckets.get(PRESENT);
    private static List<String> absentStatuses = statusBuckets.get(ABSENT);

    public ServiceDelivery(ServiceDelivery__c delivery) {
        this.delivery = delivery;
    }

    public Boolean isPresent() {
        return presentStatuses.contains(delivery.AttendanceStatus__c);
    }

    public Boolean isAbsent() {
        return absentStatuses.contains(delivery.AttendanceStatus__c);
    }

    public Boolean isDelivered() {
        return delivery.Quantity__c > 0 && delivery.DeliveryDate__c != null;
    }

    public Id getId() {
        return delivery.Id;
    }

    public Date getDeliveryDate() {
        return delivery.DeliveryDate__c;
    }

    public Id getLookupId(SObjectField lookupField) {
        return (Id) delivery.get(lookupField);
    }
}