force-app/main/default/objects/ServiceDelivery__c/ServiceDelivery__c.object-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomObject>
    <label>Service Delivery</label>
    <nameField>
        <label>Service Delivery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceDelivery__c/fields/AttendanceStatus__c.field-meta.xml
<CustomField>
    <fullName>AttendanceStatus__c</fullName>
    <label>Attendance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Present</fullName>
            </value>
            <value>
                <fullName>Unexcused Absence</fullName>
            </value>
            <value>
                <fullName>Excused Absence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AttendanceSystemAccess.cls
public without sharing class AttendanceSystemAccess {
    private QueryBuilder queryBuilder = new QueryBuilder();

    public List<ServiceDelivery__c> getAttendanceRecords(
        SObjectField field,
        Set<Id> recordIds,
        List<String> statuses
    ) {
        queryBuilder
            .reset()
            .withSelectFields(
                new List<String>{
                    String.valueOf(field),
                    String.valueOf(ServiceDelivery__c.AttendanceStatus__c)
                }
            )
            .withSObjectType(ServiceDelivery__c.SObjectType)
            .addCondition(String.valueOf(field) + ' IN :recordIds')
            .addCondition(
                String.valueOf(ServiceDelivery__c.AttendanceStatus__c) + ' IN :statuses'
            )
            .withOrderBy(String.valueOf(field));

        return Database.query(queryBuilder.buildSoqlQuery());
    }

    public void updateRecords(List<SObject> sObjects) {
        update sObjects;
    }
}