force-app/main/default/objects/ProgramEngagement__c/ProgramEngagement__c.object-meta.xml
<CustomObject>
    <label>Program Engagement</label>
    <nameField>
        <label>Program Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramEngagement__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Engagements</relationshipLabel>
    <relationshipName>Program_Engagements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceParticipant__c/ServiceParticipant__c.object-meta.xml
<CustomObject>
    <label>Service Participant</label>
    <nameField>
        <label>Service Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceParticipant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Participants</relationshipLabel>
    <relationshipName>ServiceParticipants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceParticipant__c/fields/ProgramEngagement__c.field-meta.xml
<CustomField>
    <fullName>ProgramEngagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Engagement</label>
    <referenceTo>ProgramEngagement__c</referenceTo>
    <relationshipLabel>Service Participants</relationshipLabel>
    <relationshipName>Service_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceParticipant__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Participants</relationshipLabel>
    <relationshipName>ServiceParticipants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceParticipant__c/fields/ServiceSchedule__c.field-meta.xml
<CustomField>
    <fullName>ServiceSchedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Schedule</label>
    <referenceTo>ServiceSchedule__c</referenceTo>
    <relationshipLabel>Service Participants</relationshipLabel>
    <relationshipName>Service_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/ServiceSchedule__c.object-meta.xml
<CustomObject>
    <label>Service Schedule</label>
    <nameField>
        <label>Service Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceSchedule__c/fields/OtherServiceProvider__c.field-meta.xml
<CustomField>
    <fullName>OtherServiceProvider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Other Service Provider</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Schedules (Other Service Provider)</relationshipLabel>
    <relationshipName>Service_Schedules1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/fields/PrimaryServiceProvider__c.field-meta.xml
<CustomField>
    <fullName>PrimaryServiceProvider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Service Provider</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Schedules</relationshipLabel>
    <relationshipName>Service_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Schedules</relationshipLabel>
    <relationshipName>Service_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceSession__c/ServiceSession__c.object-meta.xml
<CustomObject>
    <label>Service Session</label>
    <nameField>
        <label>Service Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceSession__c/fields/OtherServiceProvider__c.field-meta.xml
<CustomField>
    <fullName>OtherServiceProvider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Other Service Provider</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Sessions (Other Service Provider)</relationshipLabel>
    <relationshipName>ServiceSessions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceSession__c/fields/PrimaryServiceProvider__c.field-meta.xml
<CustomField>
    <fullName>PrimaryServiceProvider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Service Provider</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Sessions</relationshipLabel>
    <relationshipName>ServiceSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceSession__c/fields/ServiceSchedule__c.field-meta.xml
<CustomField>
    <fullName>ServiceSchedule__c</fullName>
    <label>Service Schedule</label>
    <referenceTo>ServiceSchedule__c</referenceTo>
    <relationshipLabel>Service Sessions</relationshipLabel>
    <relationshipName>Service_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ServiceScheduleDomain.cls
/*
 *
 *  * Copyright (c) 2020, salesforce.com, inc.
 *  * All rights reserved.
 *  * SPDX-License-Identifier: BSD-3-Clause
 *  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 */

public with sharing class ServiceScheduleDomain {
    public void commitChangesToModel(ServiceScheduleModel model) {
        upsertSchedule(model.serviceSchedule);
        setSessionDefaults(model);
        insertRelatedRecords(stripExistingRecords(model.serviceSessions));
        generateParticipants(model);
        insertRelatedRecords(stripExistingRecords(model.serviceParticipants));
    }

    public void upsertSchedule(ServiceSchedule__c schedule) {
        if (schedule.Id == null) {
            validateCreateAccess(new List<SObject>{ schedule });
            insert schedule;
        } else {
            validateUpdateAccess(new List<SObject>{ schedule });
            update schedule;
        }
    }

    public void deleteSessions(List<ServiceSession__c> sessionsToDelete) {
        if (
            !PermissionValidator.getInstance()
                .hasObjectAccess(
                    ServiceSession__c.SObjectType,
                    PermissionValidator.CRUDAccessType.DELETEABLE
                )
        ) {
            throw new ServiceScheduleDomainException(Label.Delete_Operation_Exception);
        }

        delete sessionsToDelete;
    }

    private List<SObject> stripExistingRecords(List<SObject> sObjects) {
        List<SObject> sObjectsNotYetInserted = new List<SObject>();
        for (SObject sObj : sObjects) {
            if (sObj.Id == null) {
                sObjectsNotYetInserted.add(sObj);
            }
        }
        return sObjectsNotYetInserted;
    }

    private void insertRelatedRecords(List<SObject> sObjects) {
        validateCreateAccess(sObjects);
        insert sObjects;
    }

    private void setSessionDefaults(ServiceScheduleModel model) {
        for (ServiceSession__c session : model.serviceSessions) {
            session.ServiceSchedule__c = model.serviceSchedule.Id;
            session.PrimaryServiceProvider__c = model.serviceSchedule.PrimaryServiceProvider__c;
            session.OtherServiceProvider__c = model.serviceSchedule.OtherServiceProvider__c;
        }
    }

    public void insertParticipants(
        List<ProgramEngagement__c> engagements,
        ServiceSchedule__c schedule
    ) {
        List<ServiceParticipant__c> participants = new List<ServiceParticipant__c>();
        for (ProgramEngagement__c engagement : engagements) {
            participants.add(createServiceParticipant(engagement, schedule));
        }
        insertRelatedRecords((List<SObject>) participants);
    }

    private void generateParticipants(ServiceScheduleModel model) {
        for (ProgramEngagement__c engagement : model.selectedEngagements) {
            model.serviceParticipants.add(
                createServiceParticipant(engagement, model.serviceSchedule)
            );
        }
    }

    private ServiceParticipant__c createServiceParticipant(
        ProgramEngagement__c engagement,
        ServiceSchedule__c schedule
    ) {
        return new ServiceParticipant__c(
            Name = (engagement.Contact__r.Name + ' - ' + schedule.Name).abbreviate(80),
            ServiceSchedule__c = schedule.Id,
            Service__c = schedule.Service__c,
            ProgramEngagement__c = engagement.Id,
            Contact__c = engagement.Contact__c
        );
    }

    @TestVisible
    private void validateUpdateAccess(List<SObject> sObjects) {
        if (sObjects == null || sObjects.isEmpty()) {
            return;
        }

        Boolean hasObjectPermissions;
        Boolean hasFieldPermissions;

        SObjectType sObjectType = sObjects[0].getSObjectType();
        hasObjectPermissions = PermissionValidator.getInstance()
            .hasObjectAccess(sObjectType, PermissionValidator.CRUDAccessType.UPDATEABLE);

        Set<String> populatedFieldNames = new Set<String>();
        for (SObject sObj : sObjects) {
            populatedFieldNames.addAll(sObj.getPopulatedFieldsAsMap().keySet());
        }

        // Id can be included in update call but is never updateable
        if (populatedFieldNames.contains('Id')) {
            populatedFieldNames.remove('Id');
        }

        hasFieldPermissions = PermissionValidator.getInstance()
            .hasFLSAccessForFields(
                sObjectType.getDescribe().getName(),
                new List<String>(populatedFieldNames),
                'update',
                false
            );

        if (!(hasObjectPermissions && hasFieldPermissions)) {
            throw new ServiceScheduleDomainException(
                System.Label.UpsertOperationException
            );
        }
    }

    private void validateCreateAccess(List<SObject> sObjects) {
        if (sObjects == null || sObjects.isEmpty()) {
            return;
        }

        Boolean hasObjectPermissions;
        Boolean hasFieldPermissions;

        SObjectType sObjectType = sObjects[0].getSObjectType();
        hasObjectPermissions = PermissionValidator.getInstance()
            .hasObjectAccess(sObjectType, PermissionValidator.CRUDAccessType.CREATEABLE);

        Set<String> populatedFieldNames = new Set<String>();
        for (SObject sObj : sObjects) {
            populatedFieldNames.addAll(sObj.getPopulatedFieldsAsMap().keySet());
        }

        hasFieldPermissions = PermissionValidator.getInstance()
            .hasFLSAccessForFields(
                sObjectType.getDescribe().getName(),
                new List<String>(populatedFieldNames),
                'insert',
                false
            );

        if (!(hasObjectPermissions && hasFieldPermissions)) {
            throw new ServiceScheduleDomainException(
                System.Label.Insert_Operation_Exception
            );
        }
    }

    public class ServiceScheduleDomainException extends Exception {
    }
}