force-app/main/default/objects/ProgramEngagement__c/ProgramEngagement__c.object-meta.xml
<CustomObject>
    <label>Program Engagement</label>
    <nameField>
        <label>Program Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramEngagement__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Engagements</relationshipLabel>
    <relationshipName>Program_Engagements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceParticipant__c/ServiceParticipant__c.object-meta.xml
<CustomObject>
    <label>Service Participant</label>
    <nameField>
        <label>Service Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceParticipant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Participants</relationshipLabel>
    <relationshipName>ServiceParticipants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceParticipant__c/fields/ProgramEngagement__c.field-meta.xml
<CustomField>
    <fullName>ProgramEngagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Engagement</label>
    <referenceTo>ProgramEngagement__c</referenceTo>
    <relationshipLabel>Service Participants</relationshipLabel>
    <relationshipName>Service_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceParticipant__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Participants</relationshipLabel>
    <relationshipName>ServiceParticipants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceParticipant__c/fields/ServiceSchedule__c.field-meta.xml
<CustomField>
    <fullName>ServiceSchedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Schedule</label>
    <referenceTo>ServiceSchedule__c</referenceTo>
    <relationshipLabel>Service Participants</relationshipLabel>
    <relationshipName>Service_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceParticipant__c/fields/SignUpDate__c.field-meta.xml
<CustomField>
    <fullName>SignUpDate__c</fullName>
    <label>Sign Up Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ServiceParticipant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waitlisted</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <default>true</default>
                <label>Enrolled</label>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/ServiceSchedule__c.object-meta.xml
<CustomObject>
    <label>Service Schedule</label>
    <nameField>
        <label>Service Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceSchedule__c/fields/ParticipantsEnrolled__c.field-meta.xml
<CustomField>
    <fullName>ParticipantsEnrolled__c</fullName>
    <inlineHelpText>The total number of Service Participants with Status set to Enrolled linked to this Service Schedule</inlineHelpText>
    <label>Participants Enrolled</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Schedules</relationshipLabel>
    <relationshipName>Service_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ServiceParticipantTriggerHandler_TEST.cls
/*
 *
 *  * Copyright (c) 2022, salesforce.com, inc.
 *  * All rights reserved.
 *  * SPDX-License-Identifier: BSD-3-Clause
 *  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 */

@IsTest
public with sharing class ServiceParticipantTriggerHandler_TEST {
    private static Contact contactRecord;
    private static Service__c service;
    public static ProgramEngagement__c engagement;
    private static List<ServiceParticipant__c> serviceParticipants;
    private static List<ServiceSchedule__c> serviceSchedules;

    @TestSetup
    private static void createServiceData() {
        // By turning off none, we turn on all
        TestUtil.turnOffFeatureGates(new Set<String>{});
        TestDataFactory.generateAttendanceData('Monthly');
    }

    // ////////// Functional Tests //////////
    @IsTest
    private static void shouldIncrementParticipantEnrolledCountOnInsert() {
        setupTest(new Set<String>{});
        requery();

        // The participant records were inserted in the setupTest method
        System.assertEquals(4, serviceSchedules[0].ParticipantsEnrolled__c);
    }

    @IsTest
    private static void shouldDecrementParticipantEnrolledCountOnDelete() {
        setupTest(new Set<String>{});

        Test.startTest();
        delete serviceParticipants[0];
        Test.stopTest();

        requery();

        System.assertEquals(3, serviceSchedules[0].ParticipantsEnrolled__c);
    }

    @IsTest
    private static void shouldIncrementParticipantEnrolledCountOnUnDelete() {
        setupTest(new Set<String>{});
        delete serviceParticipants[0];

        Test.startTest();
        undelete serviceParticipants[0];
        Test.stopTest();

        requery();
        System.assertEquals(4, serviceSchedules[0].ParticipantsEnrolled__c);
    }

    @IsTest
    private static void shouldIncrementParticipantEnrolledCountOnUpdate() {
        setupTest(new Set<String>{});
        System.assertEquals(2, serviceSchedules[0].ParticipantsEnrolled__c);

        requery();

        Test.startTest();
        serviceParticipants[3].Status__c = 'Enrolled';
        update serviceParticipants[3];
        Test.stopTest();

        requery();

        System.assertEquals(5, serviceSchedules[0].ParticipantsEnrolled__c);
    }

    @IsTest
    private static void shouldDecrementParticipantEnrolledCountOnUpdate() {
        setupTest(new Set<String>{});
        System.assertEquals(2, serviceSchedules[0].ParticipantsEnrolled__c);

        requery();

        Test.startTest();
        serviceParticipants[0].Status__c = 'Withdrawn';
        update serviceParticipants[0];
        Test.stopTest();

        requery();

        System.assertEquals(3, serviceSchedules[0].ParticipantsEnrolled__c);
    }

    @IsTest
    private static void shouldCallExecuteMethod() {
        setupTest(new Set<String>{});

        Test.startTest();
        ServiceParticipantTriggerHandler triggerHandler = new ServiceParticipantTriggerHandler();
        triggerHandler.execute();
        Test.stopTest();

        requery();

        //assert that none of the records were updated
        System.assertEquals(4, serviceSchedules[0].ParticipantsEnrolled__c);
    }

    @IsTest
    private static void shouldPassInvalidOperationType() {
        setupTest(new Set<String>{});

        Test.startTest();
        new ServiceParticipantTriggerHandler().delegate();
        Test.stopTest();

        requery();

        //assert that none of the records were updated
        System.assertEquals(4, serviceSchedules[0].ParticipantsEnrolled__c);
    }

    private static void setupTest(Set<String> featureGatesToDisable) {
        TestUtil.turnOffFeatureGates(featureGatesToDisable);
        requery();

        System.assertEquals(2, serviceSchedules[0].ParticipantsEnrolled__c);

        serviceParticipants = new List<ServiceParticipant__c>{
            new ServiceParticipant__c(
                Name = 'Test Participant 1',
                Contact__c = contactRecord.Id,
                ProgramEngagement__c = engagement.Id,
                Service__c = service.Id,
                ServiceSchedule__c = serviceSchedules[0].Id,
                SignUpDate__c = System.today()
            ),
            new ServiceParticipant__c(
                Name = 'Test Participant 2',
                Contact__c = contactRecord.Id,
                ProgramEngagement__c = engagement.Id,
                Service__c = service.Id,
                ServiceSchedule__c = serviceSchedules[0].Id,
                SignUpDate__c = System.today(),
                Status__c = 'Waitlisted'
            ),
            new ServiceParticipant__c(
                Name = 'Test Participant 3',
                Contact__c = contactRecord.Id,
                ProgramEngagement__c = engagement.Id,
                Service__c = service.Id,
                ServiceSchedule__c = serviceSchedules[0].Id,
                SignUpDate__c = System.today()
            )
        };

        insert serviceParticipants;
    }

    private static void requery() {
        contactRecord = [SELECT Id FROM Contact LIMIT 1];

        service = [SELECT Id FROM Service__c LIMIT 1];

        serviceSchedules = [SELECT Id, ParticipantsEnrolled__c FROM ServiceSchedule__c];

        engagement = [SELECT Id FROM ProgramEngagement__c LIMIT 1];

        serviceParticipants = [SELECT Id FROM ServiceParticipant__c];
    }
}