force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramCohort__c/ProgramCohort__c.object-meta.xml
<CustomObject>
    <label>Program Cohort</label>
    <nameField>
        <label>Program Cohort</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramCohort__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Cohorts</relationshipLabel>
    <relationshipName>ProgramCohorts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramEngagement__c/ProgramEngagement__c.object-meta.xml
<CustomObject>
    <label>Program Engagement</label>
    <nameField>
        <label>Program Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramEngagement__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Engagements</relationshipLabel>
    <relationshipName>Program_Engagements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramEngagement__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Engagements</relationshipLabel>
    <relationshipName>Program_Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramEngagement__c/fields/ProgramCohort__c.field-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomField>
    <fullName>ProgramCohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Cohort</label>
    <referenceTo>ProgramCohort__c</referenceTo>
    <relationshipLabel>Program Engagements</relationshipLabel>
    <relationshipName>ProgramEngagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramEngagement__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>A Contact&#39;s stage in a Program Engagement. Picklist values are determined by your Admin. Don&#39;t delete or modify the API Name of the Active And Enrolled picklist values as they are referenced in PMM reports.</description>
    <inlineHelpText>These Picklist values describe a Contact&#39;s stage of engagement in a Program and are displayed in a Path. Values are determined by your Admin.</inlineHelpText>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Application Denied</fullName>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Program__c.field-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/selectParticipantSelector_TEST.cls
@IsTest
public with sharing class selectParticipantSelector_TEST {
    @IsTest
    private static void testGetProgramEngagements() {
        ProgramTestDataFactory.insertTestData(true);

        Service__c service1 = [
            SELECT Id, Name
            FROM Service__c
            WHERE Name = 'Service 1'
            LIMIT 1
        ][0];

        List<ProgramEngagement__c> expected = new List<ProgramEngagement__c>(
            [
                SELECT
                    Id,
                    Contact__r.Name,
                    Contact__r.Email,
                    Stage__c,
                    Program__r.Name,
                    ProgramCohort__c
                FROM ProgramEngagement__c
                WHERE
                    (Stage__c = 'ENROLLED'
                    OR Stage__c = 'ACTIVE')
                    AND Program__c IN (
                        SELECT Program__c
                        FROM Service__c
                        WHERE Id = :service1.Id
                    )
                ORDER BY Contact__r.Name ASC
            ]
        );

        Test.startTest();
        SelectParticipantSelector selector = new SelectParticipantSelector();
        List<ProgramEngagement__c> actual = selector.getProgramEngagements(service1.Id);
        Test.stopTest();
        System.assert(!actual.isEmpty());
        System.assertEquals(
            expected.size(),
            actual.size(),
            'Expected that both the actual and expected list size are the same'
        );
        System.assertEquals(
            expected[0].ProgramCohort__c,
            actual[0].ProgramCohort__c,
            'Expected that both the actual and expected list are associated to the same program cohort'
        );
    }

    @IsTest
    private static void testGetProgramEngagementsNoAccess() {
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
        Integer random = Integer.valueOf(math.rint(math.random() * 1000000));
        User u = new User(
            Alias = 'stand',
            Email = 'standarduser1@' + random + '.example.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'StandardUser',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = p.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'standarduser1@' + random + '.example.com'
        );

        ProgramTestDataFactory.insertTestData(true);

        Service__c service1 = [
            SELECT Id, Name
            FROM Service__c
            WHERE Name = 'Service 1'
            LIMIT 1
        ][0];

        List<ProgramEngagement__c> expected = new List<ProgramEngagement__c>(
            [
                SELECT
                    Id,
                    Contact__r.Name,
                    Contact__r.Email,
                    Stage__c,
                    Program__r.Name,
                    ProgramCohort__c
                FROM ProgramEngagement__c
                WHERE
                    (Stage__c = 'ENROLLED'
                    OR Stage__c = 'ACTIVE')
                    AND Program__c IN (
                        SELECT Program__c
                        FROM Service__c
                        WHERE Id = :service1.Id
                    )
                ORDER BY Contact__r.Name ASC
            ]
        );

        Test.startTest();
        System.runAs(u) {
            SelectParticipantSelector selector = new SelectParticipantSelector();
            List<ProgramEngagement__c> actual = selector.getProgramEngagements(
                service1.Id
            );
            System.assertEquals(
                new List<ProgramEngagement__c>(),
                actual,
                'Expected the actual is an empty list of program engagements since the user does not have access to the object'
            );
        }

        Test.stopTest();
    }

    @IsTest
    private static void testGetProgramCohorts() {
        ProgramTestDataFactory.insertTestData(true);

        Service__c service1 = [
            SELECT Id, Name
            FROM Service__c
            WHERE Name = 'Service 1'
            LIMIT 1
        ][0];

        List<ProgramCohort__c> expected = new List<ProgramCohort__c>(
            [
                SELECT Id, Name
                FROM ProgramCohort__c
                WHERE
                    Program__c IN (
                        SELECT Program__c
                        FROM Service__c
                        WHERE Id = :service1.Id
                    )
            ]
        );

        Test.startTest();
        SelectParticipantSelector selector = new SelectParticipantSelector();
        List<ProgramCohort__c> actual = selector.getProgramCohorts(service1.Id);
        Test.stopTest();
        System.assert(!actual.isEmpty());
        System.assertEquals(
            expected.size(),
            actual.size(),
            'Expected that both the actual and expected list size are the same'
        );

        System.assertEquals(
            expected[0].Id,
            actual[0].Id,
            'Expected that both the actual and expected list return the same program cohort id'
        );
    }

    @IsTest
    private static void testgetProgramCohortsNoAccess() {
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
        Integer random = Integer.valueOf(math.rint(math.random() * 1000000));
        User u = new User(
            Alias = 'stand',
            Email = 'standarduser1@' + random + '.example.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'StandardUser',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = p.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'standarduser1@' + random + '.example.com'
        );

        ProgramTestDataFactory.insertTestData(true);

        Service__c service1 = [
            SELECT Id, Name
            FROM Service__c
            WHERE Name = 'Service 1'
            LIMIT 1
        ][0];

        List<ProgramCohort__c> expected = new List<ProgramCohort__c>(
            [
                SELECT Id, Name
                FROM ProgramCohort__c
                WHERE
                    Program__c IN (
                        SELECT Program__c
                        FROM Service__c
                        WHERE Id = :service1.Id
                    )
            ]
        );

        Test.startTest();
        System.runAs(u) {
            SelectParticipantSelector selector = new SelectParticipantSelector();
            List<ProgramCohort__c> actual = selector.getProgramCohorts(service1.Id);
            System.assertEquals(
                new List<ProgramCohort__c>(),
                actual,
                'Expected the actual is an empty list of program cohorts since the user does not have access to the object'
            );
        }

        Test.stopTest();
    }
}