force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramEngagement__c/ProgramEngagement__c.object-meta.xml
<CustomObject>
    <label>Program Engagement</label>
    <nameField>
        <label>Program Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramEngagement__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Engagements</relationshipLabel>
    <relationshipName>Program_Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProgramService.cls
public with sharing class ProgramService {
    @TestVisible
    private ProgramEngagementSelector programEngagementSelector = new ProgramEngagementSelector();

    @TestVisible
    private ProgramSelector programSelector = new ProgramSelector();

    public Map<Id, String> getProgramNamesByIdForContact(Id contactId) {
        List<ProgramEngagement__c> programEngagements = programEngagementSelector.getProgramEngagementsByContactId(contactId);
        List<Program__c> programs = programSelector.getProgramsFromProgramEngagements(programEngagements);
        return mapProgramNamesById(programs);
    }

    public Map<Id, String> mapProgramNamesById(List<Program__c> programs) {
        Map<Id, String> programNamesById = new Map<Id, String>();
        for (Program__c program : programs) {
            programNamesById.put(program.Id, program.Name);
        }
        return programNamesById;
    }

}