force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the Program. Values are determined by your Admin.</description>
    <inlineHelpText>The status of the Program. Values are determined by your Admin.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProgramEngagement__c/ProgramEngagement__c.object-meta.xml
<CustomObject>
    <label>Program Engagement</label>
    <nameField>
        <label>Program Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramEngagement__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Engagements</relationshipLabel>
    <relationshipName>Program_Engagements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramEngagement__c/fields/NumPresentServiceDeliveries__c.field-meta.xml
<CustomField>
    <fullName>NumPresentServiceDeliveries__c</fullName>
    <label>Number of Present Service Deliveries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProgramEngagement__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Engagements</relationshipLabel>
    <relationshipName>Program_Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/NumAbsentServiceDeliveries__c.field-meta.xml
<CustomField>
    <fullName>NumAbsentServiceDeliveries__c</fullName>
    <label>Number of Absent Service Deliveries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Program__c.field-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/ServiceDelivery__c.object-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomObject>
    <label>Service Delivery</label>
    <nameField>
        <label>Service Delivery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceDelivery__c/fields/AttendanceStatus__c.field-meta.xml
<CustomField>
    <fullName>AttendanceStatus__c</fullName>
    <label>Attendance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Present</fullName>
            </value>
            <value>
                <fullName>Unexcused Absence</fullName>
            </value>
            <value>
                <fullName>Excused Absence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Deliveries</relationshipLabel>
    <relationshipName>Service_Deliveries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/ProgramEngagement__c.field-meta.xml
<CustomField>
    <fullName>ProgramEngagement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program Engagement</label>
    <referenceTo>ProgramEngagement__c</referenceTo>
    <relationshipLabel>Service Deliveries</relationshipLabel>
    <relationshipName>ServiceDeliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/Quantity__c.field-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomField>
    <fullName>Quantity__c</fullName>
    <description>A 2-decimal numeric field for Quantity of a Service Delivery expressed in the Unit of Measurement in the Service. For example, 30 minutes of tutoring where the Unit of Measure is hours, Quantity is .50.</description>
    <inlineHelpText>A 2-decimal numeric field for Quantity of a Service Delivery expressed in the Unit of Measurement in the Service. For example, 30 minutes of tutoring where the Unit of Measure is hours, Quantity is .50.</inlineHelpText>
    <label>Quantity</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Deliveries</relationshipLabel>
    <relationshipName>ServiceDeliveries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/ServiceSchedule__c.field-meta.xml
<CustomField>
    <fullName>ServiceSchedule__c</fullName>
    <formula>ServiceSession__r.ServiceSchedule__c</formula>
    <label>Service Schedule</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/ServiceSession__c.field-meta.xml
<CustomField>
    <fullName>ServiceSession__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Session</label>
    <referenceTo>ServiceSession__c</referenceTo>
    <relationshipLabel>Service Deliveries</relationshipLabel>
    <relationshipName>Service_Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/ServiceSchedule__c.object-meta.xml
<CustomObject>
    <label>Service Schedule</label>
    <nameField>
        <label>Service Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceSchedule__c/fields/FirstSessionEnd__c.field-meta.xml
<CustomField>
    <fullName>FirstSessionEnd__c</fullName>
    <label>First Session End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/fields/FirstSessionStart__c.field-meta.xml
<CustomField>
    <fullName>FirstSessionStart__c</fullName>
    <defaultValue>NOW() + ((30 - MOD( Minute( ( TIMEVALUE( NOW() ) ) ), 30 )) / 60)/24</defaultValue>
    <label>First Session Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>One Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/fields/NumAbsentServiceDeliveries__c.field-meta.xml
<CustomField>
    <fullName>NumAbsentServiceDeliveries__c</fullName>
    <label>Number of Absent Service Deliveries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/fields/NumPresentServiceDeliveries__c.field-meta.xml
<CustomField>
    <fullName>NumPresentServiceDeliveries__c</fullName>
    <label>Number of Present Service Deliveries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/fields/OtherServiceProvider__c.field-meta.xml
<CustomField>
    <fullName>OtherServiceProvider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Other Service Provider</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Schedules (Other Service Provider)</relationshipLabel>
    <relationshipName>Service_Schedules1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/fields/PrimaryServiceProvider__c.field-meta.xml
<CustomField>
    <fullName>PrimaryServiceProvider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Service Provider</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Schedules</relationshipLabel>
    <relationshipName>Service_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Schedules</relationshipLabel>
    <relationshipName>Service_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceSession__c/ServiceSession__c.object-meta.xml
<CustomObject>
    <label>Service Session</label>
    <nameField>
        <label>Service Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceSession__c/fields/OtherServiceProvider__c.field-meta.xml
<CustomField>
    <fullName>OtherServiceProvider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Other Service Provider</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Sessions (Other Service Provider)</relationshipLabel>
    <relationshipName>ServiceSessions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceSession__c/fields/PrimaryServiceProvider__c.field-meta.xml
<CustomField>
    <fullName>PrimaryServiceProvider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Service Provider</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Sessions</relationshipLabel>
    <relationshipName>ServiceSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceSession__c/fields/ServiceSchedule__c.field-meta.xml
<CustomField>
    <fullName>ServiceSchedule__c</fullName>
    <label>Service Schedule</label>
    <referenceTo>ServiceSchedule__c</referenceTo>
    <relationshipLabel>Service Sessions</relationshipLabel>
    <relationshipName>Service_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ServiceSession__c/fields/SessionEnd__c.field-meta.xml
<CustomField>
    <fullName>SessionEnd__c</fullName>
    <label>Session End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceSession__c/fields/SessionStart__c.field-meta.xml
<CustomField>
    <fullName>SessionStart__c</fullName>
    <label>Session Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceSession__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ServiceScheduleRollupsSchedulable_TEST.cls
/*
 *
 *  * Copyright (c) 2022, salesforce.com, inc.
 *  * All rights reserved.
 *  * SPDX-License-Identifier: BSD-3-Clause
 *  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 */
@IsTest
private class ServiceScheduleRollupsSchedulable_TEST {
    private static Id accountRecordId;
    private static Contact contactRecord;
    private static Service__c service;
    private static ProgramEngagement__c programEngagement;
    private static Program__c program;
    private static List<ServiceSchedule__c> serviceSchedules;
    private static List<ServiceSession__c> sessions;
    private static List<ServiceDelivery__c> serviceDeliveries;
    private static final String PRESENT_STATUS = 'Present';
    private static final String ABSENCE_STATUS = 'Excused Absence';

    @TestSetup
    static void setupTestData() {
        TestUtil.turnOffFeatureGates();
        TestDataFactory.generateAttendanceData('Monthly');
    }

    @IsTest
    private static void shouldIncrementCountOnInsert() {
        testDataSetup();

        Test.startTest();

        ServiceScheduleRollupsSchedulable scheduleRollups = new ServiceScheduleRollupsSchedulable();
        Database.executeBatch(scheduleRollups);

        Test.stopTest();

        List<ServiceSchedule__c> schedules = [
            SELECT Id, NumAbsentServiceDeliveries__c, NumPresentServiceDeliveries__c
            FROM ServiceSchedule__c
        ];

        System.assertEquals(4, schedules[0].NumPresentServiceDeliveries__c);
        System.assertEquals(1, schedules[0].NumAbsentServiceDeliveries__c);
        System.assertEquals(1, schedules[1].NumPresentServiceDeliveries__c);
        System.assertEquals(0, schedules[1].NumAbsentServiceDeliveries__c);
    }

    @IsTest
    private static void shouldIncrementCountOnUpdate() {
        testDataSetup();

        Test.startTest();
        TestUtil.turnOffFeatureGates();
        serviceDeliveries[3].AttendanceStatus__c = ABSENCE_STATUS;
        serviceDeliveries[3].Quantity__c = 0;
        update serviceDeliveries[3];

        ServiceScheduleRollupsSchedulable scheduleRollups = new ServiceScheduleRollupsSchedulable();
        Database.executeBatch(scheduleRollups);

        Test.stopTest();
        requery();

        System.assertEquals(3, serviceSchedules[0].NumPresentServiceDeliveries__c);
        System.assertEquals(2, serviceSchedules[0].NumAbsentServiceDeliveries__c);
        System.assertEquals(1, serviceSchedules[1].NumPresentServiceDeliveries__c);
        System.assertEquals(0, serviceSchedules[1].NumAbsentServiceDeliveries__c);
    }

    @IsTest
    private static void shouldDecrementCountOnDelete() {
        testDataSetup();

        Test.startTest();
        TestUtil.turnOffFeatureGates();
        delete serviceDeliveries[3];

        ServiceScheduleRollupsSchedulable scheduleRollups = new ServiceScheduleRollupsSchedulable();
        Database.executeBatch(scheduleRollups);

        Test.stopTest();
        requery();

        System.assertEquals(3, serviceSchedules[0].NumPresentServiceDeliveries__c);
        System.assertEquals(1, serviceSchedules[0].NumAbsentServiceDeliveries__c);
        System.assertEquals(1, serviceSchedules[1].NumPresentServiceDeliveries__c);
        System.assertEquals(0, serviceSchedules[1].NumAbsentServiceDeliveries__c);
    }

    @IsTest
    private static void shouldResetParentsWithoutDeliveries() {
        testDataSetup();

        Test.startTest();
        TestUtil.turnOffFeatureGates();

        List<ServiceDelivery__c> deliveries = [
            SELECT Id
            FROM ServiceDelivery__c
            WHERE ServiceSession__c = :sessions[0].Id
        ];

        delete deliveries;

        List<ServiceDelivery__c> deliveriesToDelete = [
            SELECT Id
            FROM ServiceDelivery__c
            WHERE ServiceSession__c = :sessions[1].Id
        ];

        delete deliveriesToDelete;

        ServiceScheduleRollupsSchedulable scheduleRollups = new ServiceScheduleRollupsSchedulable();
        Database.executeBatch(scheduleRollups);
        Test.stopTest();
        requery();

        System.assertEquals(null, serviceSchedules[0].NumPresentServiceDeliveries__c);
        System.assertEquals(null, serviceSchedules[0].NumAbsentServiceDeliveries__c);
        System.assertEquals(1, serviceSchedules[1].NumPresentServiceDeliveries__c);
        System.assertEquals(0, serviceSchedules[1].NumAbsentServiceDeliveries__c);
    }

    @IsTest
    private static void shouldScheduleServiceScheduleRollupsBatch() {
        Test.startTest();

        //parse to cron expression
        String scheduledTime = '0 0 12 * * ?';

        ServiceScheduleRollupsSchedulable scheduleRollups = new ServiceScheduleRollupsSchedulable();
        String jobId = System.schedule(
            'Job Started At ' + scheduledTime,
            scheduledTime,
            scheduleRollups
        );

        CronTrigger cronTrigger = [
            SELECT Id, CronExpression, TimesTriggered
            FROM CronTrigger
            WHERE Id = :jobId
        ];

        //Assert the job has not run yet
        System.assertEquals(0, cronTrigger.TimesTriggered);

        Test.stopTest();
    }

    private static void testDataSetup() {
        requery();

        System.assertEquals(null, serviceSchedules[0].NumPresentServiceDeliveries__c);
        System.assertEquals(null, serviceSchedules[0].NumAbsentServiceDeliveries__c);

        ServiceSchedule__c schedule = new ServiceSchedule__c();

        schedule.Name = 'New Schedule';
        schedule.Frequency__c = 'Monthly';
        schedule.FirstSessionStart__c = DateTime.newInstance(
            System.today().year(),
            System.today().month() + 1,
            10
        );
        schedule.FirstSessionEnd__c = DateTime.newInstance(
            System.today().year(),
            System.today().month() + 1,
            10
        );
        schedule.PrimaryServiceProvider__c = contactRecord.Id;
        schedule.OtherServiceProvider__c = contactRecord.Id;
        schedule.NumPresentServiceDeliveries__c = 1;
        schedule.NumAbsentServiceDeliveries__c = 0;
        schedule.Service__c = service.Id;
        insert schedule;

        ServiceSession__c session = new ServiceSession__c();
        session.ServiceSchedule__c = schedule.Id;
        session.SessionStart__c = schedule.FirstSessionStart__c;
        session.SessionEnd__c = schedule.FirstSessionEnd__c;
        session.PrimaryServiceProvider__c = schedule.PrimaryServiceProvider__c;
        session.OtherServiceProvider__c = schedule.OtherServiceProvider__c;
        session.Status__c = 'Pending';
        insert session;

        serviceDeliveries = new List<ServiceDelivery__c>{
            new ServiceDelivery__c(
                Name = 'test',
                Service__c = service.Id,
                Contact__c = contactRecord.Id,
                ServiceSession__c = sessions[0].Id,
                ProgramEngagement__c = programEngagement.Id,
                Quantity__c = 0,
                AttendanceStatus__c = ABSENCE_STATUS,
                DeliveryDate__c = System.today() - 1
            ),
            new ServiceDelivery__c(
                Name = 'test2',
                Service__c = service.Id,
                Contact__c = contactRecord.Id,
                ServiceSession__c = sessions[0].Id,
                ProgramEngagement__c = programEngagement.Id,
                Quantity__c = 1,
                AttendanceStatus__c = PRESENT_STATUS,
                DeliveryDate__c = System.today()
            ),
            new ServiceDelivery__c(
                Name = 'test3',
                Service__c = service.Id,
                Contact__c = contactRecord.Id,
                ServiceSession__c = sessions[0].Id,
                ProgramEngagement__c = programEngagement.Id,
                Quantity__c = 1,
                AttendanceStatus__c = PRESENT_STATUS,
                DeliveryDate__c = System.today() - 5
            ),
            new ServiceDelivery__c(
                Name = 'test4',
                Service__c = service.Id,
                Contact__c = contactRecord.Id,
                ServiceSession__c = sessions[1].Id,
                ProgramEngagement__c = programEngagement.Id,
                Quantity__c = 1,
                AttendanceStatus__c = PRESENT_STATUS,
                DeliveryDate__c = System.today() - 2
            ),
            new ServiceDelivery__c(
                Name = 'test5',
                Service__c = service.Id,
                Contact__c = contactRecord.Id,
                ServiceSession__c = sessions[1].Id,
                ProgramEngagement__c = programEngagement.Id,
                Quantity__c = 1,
                AttendanceStatus__c = PRESENT_STATUS,
                DeliveryDate__c = System.today() - 5
            ),
            new ServiceDelivery__c(
                Name = 'test6',
                Service__c = service.Id,
                Contact__c = contactRecord.Id,
                ServiceSession__c = session.Id,
                ProgramEngagement__c = programEngagement.Id,
                Quantity__c = 1,
                AttendanceStatus__c = PRESENT_STATUS,
                DeliveryDate__c = System.today() - 5
            )
        };

        insert serviceDeliveries;
    }

    private static void requery() {
        accountRecordId = [SELECT Id FROM Account LIMIT 1].Id;
        contactRecord = [
            SELECT
                Id,
                NumPresentServiceDeliveries__c,
                NumAbsentServiceDeliveries__c,
                LastServiceDate__c,
                ConsecutiveAbsences__c,
                LastModifiedDate
            FROM Contact
            LIMIT 1
        ];

        service = [
            SELECT Id, NumPresentServiceDeliveries__c, NumAbsentServiceDeliveries__c
            FROM Service__c
            LIMIT 1
        ];

        serviceSchedules = [
            SELECT
                Id,
                FirstSessionStart__c,
                FirstSessionEnd__c,
                PrimaryServiceProvider__c,
                OtherServiceProvider__c,
                NumPresentServiceDeliveries__c,
                NumAbsentServiceDeliveries__c
            FROM ServiceSchedule__c
            LIMIT 2
        ];

        sessions = [
            SELECT
                Id,
                NumPresentServiceDeliveries__c,
                NumAbsentServiceDeliveries__c,
                SessionStart__c
            FROM ServiceSession__c
            ORDER BY SessionStart__c DESC
        ];

        programEngagement = [
            SELECT
                Id,
                NumPresentServiceDeliveries__c,
                NumAbsentServiceDeliveries__c,
                LastServiceDate__c,
                ConsecutiveAbsences__c
            FROM ProgramEngagement__c
            LIMIT 1
        ];

        program = [SELECT Id, Name FROM Program__c LIMIT 1];
    }
}