force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/EndDate__c.field-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomField>
    <fullName>EndDate__c</fullName>
    <description>The date the Program is scheduled to end.</description>
    <inlineHelpText>The date the Program is scheduled to end.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>The date the Program is scheduled to start.</description>
    <inlineHelpText>The date the Program is scheduled to start.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the Program. Values are determined by your Admin.</description>
    <inlineHelpText>The status of the Program. Values are determined by your Admin.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProgramEngagement__c/ProgramEngagement__c.object-meta.xml
<CustomObject>
    <label>Program Engagement</label>
    <nameField>
        <label>Program Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramEngagement__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Engagements</relationshipLabel>
    <relationshipName>Program_Engagements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramEngagement__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>The date a Contact completes or leaves the Program. If the Program Engagement stage Completed or Withdrawn, the End Date is set to TODAY() by the Process Builder process titled Template: Program Engagement Name. Clone the process template to edit it.</description>
    <inlineHelpText>The date a Contact completes or leaves the Program. If the Program Engagement stage Completed or Withdrawn, the End Date is set to TODAY() by the Process Builder process titled Template: Program Engagement Name. Clone the process template to edit it.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProgramEngagement__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Engagements</relationshipLabel>
    <relationshipName>Program_Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramEngagement__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>A Contact&#39;s relationship with the Program Engagement. Values are determined by your Admin.</description>
    <inlineHelpText>A Contact&#39;s relationship with the Program Engagement. Values are determined by your Admin.</inlineHelpText>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProgramEngagement__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>A Contact&#39;s stage in a Program Engagement. Picklist values are determined by your Admin. Don&#39;t delete or modify the API Name of the Active And Enrolled picklist values as they are referenced in PMM reports.</description>
    <inlineHelpText>These Picklist values describe a Contact&#39;s stage of engagement in a Program and are displayed in a Path. Values are determined by your Admin.</inlineHelpText>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Application Denied</fullName>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProgramEngagement__c/fields/StartDate__c.field-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomField>
    <fullName>StartDate__c</fullName>
    <description>If the Program Engagement stage is set to Enrolled or Active, the Start Date is set to TODAY() by the Process Builder process, Template: Program Engagement. Clone the template to edit it.</description>
    <inlineHelpText>If the Program Engagement Stage is Enrolled or Active, the Start Date defaults to today if left blank.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Program__c.field-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/UnitOfMeasurement__c.field-meta.xml
<CustomField>
    <fullName>UnitOfMeasurement__c</fullName>
    <description>The unit used to track the service. For example: hours, meals, sessions, deliveries, kits, etc. Defining a Unit of Measurement standardizes how you measure the delivery of the service.</description>
    <inlineHelpText>The unit used to track the service. For example: hours, meals, sessions, deliveries, kits, etc. Defining a Unit of Measurement standardizes how you measure the delivery of the service.</inlineHelpText>
    <label>Unit of Measurement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/ServiceDelivery__c.object-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomObject>
    <label>Service Delivery</label>
    <nameField>
        <label>Service Delivery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceDelivery__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Deliveries</relationshipLabel>
    <relationshipName>Service_Deliveries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/ProgramEngagement__c.field-meta.xml
<CustomField>
    <fullName>ProgramEngagement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program Engagement</label>
    <referenceTo>ProgramEngagement__c</referenceTo>
    <relationshipLabel>Service Deliveries</relationshipLabel>
    <relationshipName>ServiceDeliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Deliveries</relationshipLabel>
    <relationshipName>ServiceDeliveries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/UnitOfMeasurement__c.field-meta.xml
<CustomField>
    <fullName>UnitOfMeasurement__c</fullName>
    <description>A formula field that displays the UnitOfMeasurement__c field from the Service object.</description>
    <inlineHelpText>A formula field that displays the UnitOfMeasurement field from the Service object.</inlineHelpText>
    <formula>Service__r.UnitOfMeasurement__c</formula>
    <label>Unit of Measurement</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ServiceService_TEST.cls
/*
 *
 *  * Copyright (c) 2020, salesforce.com, inc.
 *  * All rights reserved.
 *  * SPDX-License-Identifier: BSD-3-Clause
 *  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 */

@isTest
public with sharing class ServiceService_TEST {
    @IsTest
    private static void testGetServicesEngagementsByContactId() {
        Id contactId = TestUtil.mockId(Contact.SObjectType);

        Program__c program1 = new Program__c(
            Id = TestUtil.mockId(Program__c.SObjectType),
            Name = 'Program 1',
            Status__c = 'Active',
            StartDate__c = Date.today(),
            EndDate__c = Date.today().addDays(30)
        );

        ProgramEngagement__c engagement1 = new ProgramEngagement__c(
            Name = 'Engagement 1',
            Stage__c = 'Enrolled',
            Contact__c = contactId,
            Program__c = program1.Id,
            Role__c = 'Client'
        );

        Service__c service1 = new Service__c(
            Id = TestUtil.mockId(Service__c.SObjectType),
            Name = 'Service 1',
            Program__c = program1.Id,
            Status__c = 'Active',
            UnitOfMeasurement__c = 'Hours'
        );

        List<ProgramEngagement__c> engagements = new List<ProgramEngagement__c>{
            engagement1
        };
        List<Service__c> services = new List<Service__c>{ service1 };
        TestStub engagementSelectorStub = new StubBuilder(ProgramEngagementSelector.class)
            .when('getProgramEngagementsByContactId', Id.class)
            .calledWith(contactId)
            .thenReturn(engagements)
            .build();
        TestStub serviceSelectorStub = new StubBuilder(ServiceSelector.class)
            .when('getServicesByProgramIds', Set<Id>.class)
            .calledWith(new Set<Id>{ program1.Id })
            .thenReturn(services)
            .build();

        ServiceService service = new ServiceService();
        service.serviceSelector = (ServiceSelector) serviceSelectorStub.create();
        service.engagementSelector = (ProgramEngagementSelector) engagementSelectorStub.create();

        Test.startTest();
        Map<String, List<Object>> actual = service.getServicesEngagementsByContactId(
            contactId
        );
        Test.stopTest();

        Set<String> expectedKeySet = new Set<String>{ 'engagements', 'services' };
        System.assertEquals(
            expectedKeySet,
            actual.keySet(),
            'Expected both keys to be returned.'
        );

        for (List<Object> objList : actual.values()) {
            System.assert(!objList.isEmpty());
        }

        engagementSelectorStub.assertCalledAsExpected();
        serviceSelectorStub.assertCalledAsExpected();
    }

    @IsTest
    private static void testGetServicesByProgramEngagementId() {
        Id programEngagementId = TestUtil.mockId(ProgramEngagement__c.SObjectType);

        Program__c program1 = new Program__c(
            Id = TestUtil.mockId(Program__c.SObjectType),
            Name = 'Program 1',
            Status__c = 'Active',
            StartDate__c = Date.today(),
            EndDate__c = Date.today().addDays(30)
        );

        ProgramEngagement__c engagement1 = new ProgramEngagement__c(
            Name = 'Engagement 1',
            Stage__c = 'Enrolled',
            Program__c = program1.Id,
            Role__c = 'Client'
        );

        Service__c service1 = new Service__c(
            Id = TestUtil.mockId(Service__c.SObjectType),
            Name = 'Service 1',
            Program__c = program1.Id,
            Status__c = 'Active',
            UnitOfMeasurement__c = 'Hours'
        );

        List<Service__c> services = new List<Service__c>{ service1 };
        Map<String, String> expectedValues = new Map<String, String>();
        expectedValues.put('label', Service1.Name);
        expectedValues.put('program', program1.Id);
        expectedValues.put('value', service1.Id);

        final List<object> expected = new List<Object>{ expectedValues };

        TestStub serviceSelectorStub = new StubBuilder(ServiceSelector.class)
            .when('getServicesByProgramEngagementId', Id.class)
            .calledWith(programEngagementId)
            .thenReturn(services)
            .build();

        Test.startTest();

        final ServiceService service = new ServiceService();
        service.serviceSelector = (ServiceSelector) serviceSelectorStub.create();

        final List<Object> actual = service.getServicesByProgramEngagementId(
            programEngagementId
        );

        Test.stopTest();
        System.assertEquals(
            expected,
            actual,
            'Expected that both expected and actual have the same values'
        );

        System.assertEquals(
            expected.size(),
            actual.size(),
            'Expected the size of both expected and actual are the same'
        );

        serviceSelectorStub.assertCalledAsExpected();
    }

    //Removing the service field from the fieldset
    @IsTest
    private static void testGetServiceDeliveryFieldSetsWithoutService() {
        Map<String, Object> removedServiceField;
        FieldSetService fieldSetService = new FieldSetService();
        Integer serviceFieldIndex;

        Map<String, Object> fieldSetsToReturn = fieldSetService.getFieldSetsByName(
            Schema.SObjectType.ServiceDelivery__c.getName()
        );
        Map<String, Object> serviceField = fieldSetService.getFieldForLWC(
            ServiceDelivery__c.Service__c.getDescribe()
        );
        Map<String, Object> contactField = fieldSetService.getFieldForLWC(
            ServiceDelivery__c.Contact__c.getDescribe()
        );
        Map<String, Object> engagementField = fieldSetService.getFieldForLWC(
            ServiceDelivery__c.ProgramEngagement__c.getDescribe()
        );

        //Remove the service field from the fieldset that we got back
        for (String key : fieldSetsToReturn.keySet()) {
            List<Map<String, Object>> fieldSetValues = (List<Map<String, Object>>) fieldSetsToReturn.get(
                key
            );

            if (fieldSetValues.indexOf(serviceField) > 0) {
                removedServiceField = fieldSetValues.remove(
                    fieldSetValues.indexOf(serviceField)
                );

                System.assertEquals(
                    removedServiceField,
                    serviceField,
                    'Service field was not removed from the fieldset as expected'
                );
                System.assertEquals(
                    false,
                    fieldSetValues.contains(serviceField),
                    'Service field was not removed from the fieldset'
                );
            }
        }

        TestStub fieldSetServiceStub = new StubBuilder(fieldSetService.class)
            .when('getFieldSetsByName', String.class)
            .calledWith(Schema.SObjectType.ServiceDelivery__c.getName())
            .thenReturn(fieldSetsToReturn)
            .when('getFieldForLWC', DescribeFieldResult.class)
            .calledWith(ServiceDelivery__c.Service__c.getDescribe())
            .thenReturn(serviceField)
            .when('getFieldForLWC', DescribeFieldResult.class)
            .calledWith(ServiceDelivery__c.Contact__c.getDescribe())
            .thenReturn(contactField)
            .when('getFieldForLWC', DescribeFieldResult.class)
            .calledWith(ServiceDelivery__c.ProgramEngagement__c.getDescribe())
            .thenReturn(engagementField)
            .build();

        ServiceService service = new ServiceService();
        service.fieldSetService = (FieldSetService) fieldSetServiceStub.create();

        Test.startTest();
        Map<String, Object> actualFieldSets = service.getServiceDeliveryFieldSets();
        Test.stopTest();

        for (String key : actualFieldSets.keySet()) {
            List<Map<String, Object>> fieldSetValues = (List<Map<String, Object>>) actualFieldSets.get(
                key
            );

            serviceFieldIndex = fieldSetValues.indexOf(serviceField);

            System.assert(
                serviceFieldIndex > 0,
                'Expected the service field to be added to the fieldset.'
            );
        }

        fieldSetServiceStub.assertCalledAsExpected();
    }

    //Do not remove any fields from the fieldset
    @IsTest
    private static void testGetServiceDeliveryFieldSetsWithAllFields() {
        Map<String, Object> removedServiceField;
        FieldSetService fieldSetService = new FieldSetService();
        Integer serviceFieldIndex;

        Map<String, Object> fieldSetsToReturn = fieldSetService.getFieldSetsByName(
            Schema.SObjectType.ServiceDelivery__c.getName()
        );
        Map<String, Object> serviceField = fieldSetService.getFieldForLWC(
            ServiceDelivery__c.Service__c.getDescribe()
        );
        Map<String, Object> contactField = fieldSetService.getFieldForLWC(
            ServiceDelivery__c.Contact__c.getDescribe()
        );
        Map<String, Object> engagementField = fieldSetService.getFieldForLWC(
            ServiceDelivery__c.ProgramEngagement__c.getDescribe()
        );

        TestStub fieldSetServiceStub = new StubBuilder(fieldSetService.class)
            .when('getFieldSetsByName', String.class)
            .calledWith(Schema.SObjectType.ServiceDelivery__c.getName())
            .thenReturn(fieldSetsToReturn)
            .when('getFieldForLWC', DescribeFieldResult.class)
            .calledWith(ServiceDelivery__c.Service__c.getDescribe())
            .thenReturn(serviceField)
            .when('getFieldForLWC', DescribeFieldResult.class)
            .calledWith(ServiceDelivery__c.Contact__c.getDescribe())
            .thenReturn(contactField)
            .when('getFieldForLWC', DescribeFieldResult.class)
            .calledWith(ServiceDelivery__c.ProgramEngagement__c.getDescribe())
            .thenReturn(engagementField)
            .build();

        ServiceService service = new ServiceService();
        service.fieldSetService = (FieldSetService) fieldSetServiceStub.create();

        Test.startTest();
        Map<String, Object> actualFieldSets = service.getServiceDeliveryFieldSets();
        Test.stopTest();

        for (String key : actualFieldSets.keySet()) {
            List<Map<String, Object>> fieldSetValues = (List<Map<String, Object>>) actualFieldSets.get(
                key
            );

            serviceFieldIndex = fieldSetValues.indexOf(serviceField);

            System.assert(
                serviceFieldIndex > 0,
                'Expected the service field to be added to the fieldset.'
            );
        }

        fieldSetServiceStub.assertCalledAsExpected();
    }

    //Removing the contact and service field from the fieldset
    @IsTest
    private static void testGetServiceDeliveryFieldSetsWithoutContactAndService() {
        Map<String, Object> removedServiceField;
        Map<String, Object> removedContactField;
        FieldSetService fieldSetService = new FieldSetService();
        Integer serviceFieldIndex;

        Map<String, Object> fieldSetsToReturn = fieldSetService.getFieldSetsByName(
            Schema.SObjectType.ServiceDelivery__c.getName()
        );
        Map<String, Object> serviceField = fieldSetService.getFieldForLWC(
            ServiceDelivery__c.Service__c.getDescribe()
        );
        Map<String, Object> contactField = fieldSetService.getFieldForLWC(
            ServiceDelivery__c.Contact__c.getDescribe()
        );
        Map<String, Object> engagementField = fieldSetService.getFieldForLWC(
            ServiceDelivery__c.ProgramEngagement__c.getDescribe()
        );

        //Remove the contact and service field from the fieldset that we got back
        for (String key : fieldSetsToReturn.keySet()) {
            List<Map<String, Object>> fieldSetValues = (List<Map<String, Object>>) fieldSetsToReturn.get(
                key
            );

            if (fieldSetValues.indexOf(serviceField) >= 0) {
                removedServiceField = fieldSetValues.remove(
                    fieldSetValues.indexOf(serviceField)
                );

                System.assertEquals(
                    removedServiceField,
                    serviceField,
                    'Service field was not removed from the fieldset as expected'
                );

                System.assertEquals(
                    false,
                    fieldSetValues.contains(serviceField),
                    'Service field was not removed from the fieldset'
                );
            }

            if (fieldSetValues.indexOf(contactField) >= 0) {
                removedContactField = fieldSetValues.remove(
                    fieldSetValues.indexOf(contactField)
                );

                System.assertEquals(
                    removedContactField,
                    contactField,
                    'Contact field was not removed from the fieldset as expected'
                );

                System.assertEquals(
                    false,
                    fieldSetValues.contains(contactField),
                    'Contact field was not removed from the fieldset'
                );
            }
        }

        TestStub fieldSetServiceStub = new StubBuilder(fieldSetService.class)
            .when('getFieldSetsByName', String.class)
            .calledWith(Schema.SObjectType.ServiceDelivery__c.getName())
            .thenReturn(fieldSetsToReturn)
            .when('getFieldForLWC', DescribeFieldResult.class)
            .calledWith(ServiceDelivery__c.Service__c.getDescribe())
            .thenReturn(serviceField)
            .when('getFieldForLWC', DescribeFieldResult.class)
            .calledWith(ServiceDelivery__c.Contact__c.getDescribe())
            .thenReturn(contactField)
            .when('getFieldForLWC', DescribeFieldResult.class)
            .calledWith(ServiceDelivery__c.ProgramEngagement__c.getDescribe())
            .thenReturn(engagementField)
            .build();

        ServiceService service = new ServiceService();
        service.fieldSetService = (FieldSetService) fieldSetServiceStub.create();

        Test.startTest();
        Map<String, Object> actualFieldSets = service.getServiceDeliveryFieldSets();
        Test.stopTest();

        for (String key : actualFieldSets.keySet()) {
            List<Map<String, Object>> fieldSetValues = (List<Map<String, Object>>) actualFieldSets.get(
                key
            );

            serviceFieldIndex = fieldSetValues.indexOf(serviceField);

            System.assertNotEquals(
                serviceFieldIndex,
                -1,
                'Expected the service field to be added to the fieldset.'
            );
        }

        fieldSetServiceStub.assertCalledAsExpected();
    }

    //Removing the program engagement and service field from the fieldset
    @IsTest
    private static void testGetServiceDeliveryFieldSetsWithoutPEAndService() {
        Map<String, Object> removedServiceField;
        Map<String, Object> removedEngagementField;
        FieldSetService fieldSetService = new FieldSetService();
        Integer serviceFieldIndex;
        Integer engagementFieldIndex;

        Map<String, Object> fieldSetsToReturn = fieldSetService.getFieldSetsByName(
            Schema.SObjectType.ServiceDelivery__c.getName()
        );
        Map<String, Object> serviceField = fieldSetService.getFieldForLWC(
            ServiceDelivery__c.Service__c.getDescribe()
        );
        Map<String, Object> contactField = fieldSetService.getFieldForLWC(
            ServiceDelivery__c.Contact__c.getDescribe()
        );
        Map<String, Object> engagementField = fieldSetService.getFieldForLWC(
            ServiceDelivery__c.ProgramEngagement__c.getDescribe()
        );

        //Remove the program engagement and service field from the fieldset that we got back
        for (String key : fieldSetsToReturn.keySet()) {
            List<Map<String, Object>> fieldSetValues = (List<Map<String, Object>>) fieldSetsToReturn.get(
                key
            );

            if (fieldSetValues.indexOf(serviceField) >= 0) {
                removedServiceField = fieldSetValues.remove(
                    fieldSetValues.indexOf(serviceField)
                );

                System.assertEquals(
                    removedServiceField,
                    serviceField,
                    'Service field was not removed from the fieldset as expected'
                );

                System.assertEquals(
                    false,
                    fieldSetValues.contains(serviceField),
                    'Service field was not removed from the fieldset'
                );
            }

            if (fieldSetValues.indexOf(engagementField) >= 0) {
                removedEngagementField = fieldSetValues.remove(
                    fieldSetValues.indexOf(engagementField)
                );

                System.assertEquals(
                    removedEngagementField,
                    engagementField,
                    'Program Engagement field was not removed from the fieldset as expected'
                );

                System.assertEquals(
                    false,
                    fieldSetValues.contains(engagementField),
                    'Program Engagement field was not removed from the fieldset'
                );
            }
        }

        TestStub fieldSetServiceStub = new StubBuilder(fieldSetService.class)
            .when('getFieldSetsByName', String.class)
            .calledWith(Schema.SObjectType.ServiceDelivery__c.getName())
            .thenReturn(fieldSetsToReturn)
            .when('getFieldForLWC', DescribeFieldResult.class)
            .calledWith(ServiceDelivery__c.Service__c.getDescribe())
            .thenReturn(serviceField)
            .when('getFieldForLWC', DescribeFieldResult.class)
            .calledWith(ServiceDelivery__c.Contact__c.getDescribe())
            .thenReturn(contactField)
            .when('getFieldForLWC', DescribeFieldResult.class)
            .calledWith(ServiceDelivery__c.ProgramEngagement__c.getDescribe())
            .thenReturn(engagementField)
            .build();

        ServiceService service = new ServiceService();
        service.fieldSetService = (FieldSetService) fieldSetServiceStub.create();

        Test.startTest();
        Map<String, Object> actualFieldSets = service.getServiceDeliveryFieldSets();
        Test.stopTest();

        for (String key : actualFieldSets.keySet()) {
            List<Map<String, Object>> fieldSetValues = (List<Map<String, Object>>) actualFieldSets.get(
                key
            );

            serviceFieldIndex = fieldSetValues.indexOf(serviceField);
            engagementFieldIndex = fieldSetValues.indexOf(engagementField);

            System.assertNotEquals(
                serviceFieldIndex,
                -1,
                'Expected the service field to be added to the fieldset.'
            );

            System.assertEquals(
                engagementFieldIndex,
                -1,
                'Expected the program engagement field to be removed from the fieldset.'
            );
        }

        fieldSetServiceStub.assertCalledAsExpected();
    }

    //Removing the contact, program engagement and service field from the fieldset
    @IsTest
    private static void testGetServiceDeliveryFieldSetsWithoutContactPEAndService() {
        Map<String, Object> removedServiceField;
        Map<String, Object> removedContactField;
        Map<String, Object> removedEngagementField;
        FieldSetService fieldSetService = new FieldSetService();
        Integer serviceFieldIndex;
        Integer contactFieldIndex;
        Integer engagementFieldIndex;

        Map<String, Object> fieldSetsToReturn = fieldSetService.getFieldSetsByName(
            Schema.SObjectType.ServiceDelivery__c.getName()
        );
        Map<String, Object> serviceField = fieldSetService.getFieldForLWC(
            ServiceDelivery__c.Service__c.getDescribe()
        );
        Map<String, Object> contactField = fieldSetService.getFieldForLWC(
            ServiceDelivery__c.Contact__c.getDescribe()
        );
        Map<String, Object> engagementField = fieldSetService.getFieldForLWC(
            ServiceDelivery__c.ProgramEngagement__c.getDescribe()
        );

        //Remove the contact, program engagement and service field from the fieldset that we got back
        for (String key : fieldSetsToReturn.keySet()) {
            List<Map<String, Object>> fieldSetValues = (List<Map<String, Object>>) fieldSetsToReturn.get(
                key
            );

            if (fieldSetValues.indexOf(serviceField) >= 0) {
                removedServiceField = fieldSetValues.remove(
                    fieldSetValues.indexOf(serviceField)
                );

                System.assertEquals(
                    removedServiceField,
                    serviceField,
                    'Service field was not removed from the fieldset as expected'
                );

                System.assertEquals(
                    false,
                    fieldSetValues.contains(serviceField),
                    'Service field was not removed from the fieldset'
                );
            }

            if (fieldSetValues.indexOf(contactField) >= 0) {
                removedContactField = fieldSetValues.remove(
                    fieldSetValues.indexOf(contactField)
                );

                System.assertEquals(
                    removedContactField,
                    contactField,
                    'Contact field was not removed from the fieldset as expected'
                );

                System.assertEquals(
                    false,
                    fieldSetValues.contains(contactField),
                    'Contact field was not removed from the fieldset'
                );
            }

            if (fieldSetValues.indexOf(engagementField) >= 0) {
                removedEngagementField = fieldSetValues.remove(
                    fieldSetValues.indexOf(engagementField)
                );

                System.assertEquals(
                    removedEngagementField,
                    engagementField,
                    'Program Engagement field was not removed from the fieldset as expected'
                );

                System.assertEquals(
                    false,
                    fieldSetValues.contains(engagementField),
                    'Program Engagement field was not removed from the fieldset'
                );
            }
        }

        TestStub fieldSetServiceStub = new StubBuilder(fieldSetService.class)
            .when('getFieldSetsByName', String.class)
            .calledWith(Schema.SObjectType.ServiceDelivery__c.getName())
            .thenReturn(fieldSetsToReturn)
            .when('getFieldForLWC', DescribeFieldResult.class)
            .calledWith(ServiceDelivery__c.Service__c.getDescribe())
            .thenReturn(serviceField)
            .when('getFieldForLWC', DescribeFieldResult.class)
            .calledWith(ServiceDelivery__c.Contact__c.getDescribe())
            .thenReturn(contactField)
            .when('getFieldForLWC', DescribeFieldResult.class)
            .calledWith(ServiceDelivery__c.ProgramEngagement__c.getDescribe())
            .thenReturn(engagementField)
            .build();

        ServiceService service = new ServiceService();
        service.fieldSetService = (FieldSetService) fieldSetServiceStub.create();

        Test.startTest();
        Map<String, Object> actualFieldSets = service.getServiceDeliveryFieldSets();
        Test.stopTest();

        for (String key : actualFieldSets.keySet()) {
            List<Map<String, Object>> fieldSetValues = (List<Map<String, Object>>) actualFieldSets.get(
                key
            );

            serviceFieldIndex = fieldSetValues.indexOf(serviceField);
            contactFieldIndex = fieldSetValues.indexOf(contactField);
            engagementFieldIndex = fieldSetValues.indexOf(engagementField);

            System.assertNotEquals(
                serviceFieldIndex,
                -1,
                'Expected the service field to be added to the fieldset.'
            );

            System.assertEquals(
                contactFieldIndex,
                -1,
                'Expected the contact field to be removed from the fieldset.'
            );

            System.assertEquals(
                engagementFieldIndex,
                -1,
                'Expected the Program Engagement field to be removed from the fieldset.'
            );
        }

        fieldSetServiceStub.assertCalledAsExpected();
    }

    //Clearing the fieldset that we got back and adding just the program engagement field back
    @IsTest
    private static void testGetServiceDeliveryFieldSetsWithOneField() {
        FieldSetService fieldSetService = new FieldSetService();
        Integer serviceFieldIndex;
        Integer engagementFieldIndex;

        Map<String, Object> fieldSetsToReturn = fieldSetService.getFieldSetsByName(
            Schema.SObjectType.ServiceDelivery__c.getName()
        );
        Map<String, Object> serviceField = fieldSetService.getFieldForLWC(
            ServiceDelivery__c.Service__c.getDescribe()
        );
        Map<String, Object> engagementField = fieldSetService.getFieldForLWC(
            ServiceDelivery__c.ProgramEngagement__c.getDescribe()
        );

        //Need to remove the fields from the fieldset and add just the program engagement field

        for (String key : fieldSetsToReturn.keySet()) {
            fieldSetsToReturn.remove(key);
            fieldSetsToReturn.put(key, new List<Map<String, Object>>{ engagementField });
        }

        TestStub fieldSetServiceStub = new StubBuilder(fieldSetService.class)
            .when('getFieldSetsByName', String.class)
            .calledWith(Schema.SObjectType.ServiceDelivery__c.getName())
            .thenReturn(fieldSetsToReturn)
            .when('getFieldForLWC', DescribeFieldResult.class)
            .calledWith(ServiceDelivery__c.Service__c.getDescribe())
            .thenReturn(serviceField)
            .when('getFieldForLWC', DescribeFieldResult.class)
            .calledWith(ServiceDelivery__c.ProgramEngagement__c.getDescribe())
            .thenReturn(engagementField)
            .build();

        ServiceService service = new ServiceService();
        service.fieldSetService = (FieldSetService) fieldSetServiceStub.create();

        Test.startTest();
        Map<String, Object> actualFieldSets = service.getServiceDeliveryFieldSets();
        Test.stopTest();

        for (String key : actualFieldSets.keySet()) {
            List<Map<String, Object>> fieldSetValues = (List<Map<String, Object>>) actualFieldSets.get(
                key
            );

            serviceFieldIndex = fieldSetValues.indexOf(serviceField);
            engagementFieldIndex = fieldSetValues.indexOf(engagementField);

            System.assertNotEquals(
                serviceFieldIndex,
                -1,
                'Expected the service field to be added to the fieldset.'
            );

            System.assertNotEquals(
                engagementFieldIndex,
                -1,
                'Expected the Program Engagement field to be in the fieldset.'
            );
        }

        fieldSetServiceStub.assertCalledAsExpected();
    }
}