force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramCohort__c/ProgramCohort__c.object-meta.xml
<CustomObject>
    <label>Program Cohort</label>
    <nameField>
        <label>Program Cohort</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramCohort__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Cohorts</relationshipLabel>
    <relationshipName>ProgramCohorts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramEngagement__c/ProgramEngagement__c.object-meta.xml
<CustomObject>
    <label>Program Engagement</label>
    <nameField>
        <label>Program Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramEngagement__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Engagements</relationshipLabel>
    <relationshipName>Program_Engagements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramEngagement__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Engagements</relationshipLabel>
    <relationshipName>Program_Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramEngagement__c/fields/ProgramCohort__c.field-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomField>
    <fullName>ProgramCohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Cohort</label>
    <referenceTo>ProgramCohort__c</referenceTo>
    <relationshipLabel>Program Engagements</relationshipLabel>
    <relationshipName>ProgramEngagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramEngagement__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>A Contact&#39;s stage in a Program Engagement. Picklist values are determined by your Admin. Don&#39;t delete or modify the API Name of the Active And Enrolled picklist values as they are referenced in PMM reports.</description>
    <inlineHelpText>These Picklist values describe a Contact&#39;s stage of engagement in a Program and are displayed in a Path. Values are determined by your Admin.</inlineHelpText>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Application Denied</fullName>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceParticipant__c/ServiceParticipant__c.object-meta.xml
<CustomObject>
    <label>Service Participant</label>
    <nameField>
        <label>Service Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceParticipant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Participants</relationshipLabel>
    <relationshipName>ServiceParticipants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceParticipant__c/fields/ProgramEngagement__c.field-meta.xml
<CustomField>
    <fullName>ProgramEngagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Engagement</label>
    <referenceTo>ProgramEngagement__c</referenceTo>
    <relationshipLabel>Service Participants</relationshipLabel>
    <relationshipName>Service_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceParticipant__c/fields/ServiceSchedule__c.field-meta.xml
<CustomField>
    <fullName>ServiceSchedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Schedule</label>
    <referenceTo>ServiceSchedule__c</referenceTo>
    <relationshipLabel>Service Participants</relationshipLabel>
    <relationshipName>Service_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceSchedule__c/ServiceSchedule__c.object-meta.xml
<CustomObject>
    <label>Service Schedule</label>
    <nameField>
        <label>Service Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceSchedule__c/fields/ParticipantCapacity__c.field-meta.xml
<CustomField>
    <fullName>ParticipantCapacity__c</fullName>
    <label>Participant Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SelectParticipantModel.cls
/*
 *
 *  * Copyright (c) 2020, salesforce.com, inc.
 *  * All rights reserved.
 *  * SPDX-License-Identifier: BSD-3-Clause
 *  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 */

public with sharing class SelectParticipantModel {
    @TestVisible
    private FieldSetService fieldSetService = new FieldSetService();

    private Id serviceId;
    private Map<String, Map<String, Object>> contactFields = new Map<String, Map<String, Object>>{
        'contactName' => fieldSetService.getFieldForLWC(
            Schema.Contact.Name.getDescribe()
        ),
        'contactEmail' => fieldSetService.getFieldForLWC(
            Schema.Contact.Email.getDescribe()
        )
    };
    private Map<String, Map<String, Object>> engagementFields = new Map<String, Map<String, Object>>{
        'engagementStage' => fieldSetService.getFieldForLWC(
            Schema.ProgramEngagement__c.Stage__c.getDescribe()
        ),
        'contact' => fieldSetService.getFieldForLWC(
            Schema.ProgramEngagement__c.Contact__c.getDescribe()
        )
    };
    private Map<String, Map<String, Object>> scheduleFields = new Map<String, Map<String, Object>>{
        'capacity' => fieldSetService.getFieldForLWC(
            Schema.ServiceSchedule__c.ParticipantCapacity__c.getDescribe()
        ),
        'name' => fieldSetService.getFieldForLWC(
            Schema.ServiceSchedule__c.Name.getDescribe()
        )
    };

    @AuraEnabled
    public List<ProgramEngagement__c> programEngagements;
    @AuraEnabled
    public List<ProgramCohort__c> programCohorts;
    @AuraEnabled
    public Map<String, Map<String, String>> objectLabels;
    @AuraEnabled
    public Map<String, Map<String, Object>> fields;
    @AuraEnabled
    public Program__c program;

    public SelectParticipantModel() {
        programEngagements = new List<ProgramEngagement__c>();
        programCohorts = new List<ProgramCohort__c>();

        populateObjectLabels();
        populateFields();
    }

    private void populateObjectLabels() {
        objectLabels = new Map<String, Map<String, String>>{
            'program' => Util.getObjectLabels(Program__c.SObjectType),
            'programCohort' => Util.getObjectLabels(ProgramCohort__c.sObjectType),
            'serviceParticipant' => Util.getObjectLabels(
                ServiceParticipant__c.sObjectType
            )
        };
    }

    private void populateFields() {
        fields = contactFields;
        fields.putAll(engagementFields);
        fields.putAll(scheduleFields);
    }
}