force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramEngagement__c/ProgramEngagement__c.object-meta.xml
<CustomObject>
    <label>Program Engagement</label>
    <nameField>
        <label>Program Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramEngagement__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Engagements</relationshipLabel>
    <relationshipName>Program_Engagements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramEngagement__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Engagements</relationshipLabel>
    <relationshipName>Program_Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProgramSelector_TEST.cls
@isTest
public with sharing class ProgramSelector_TEST {
    @isTest
    private static void testGetProgramsByContactId() {
        ProgramTestDataFactory.insertTestData(true);
        Contact con = [
            SELECT Id, Name
            FROM Contact
            WHERE LastName = 'Test Contact'
            LIMIT 1
        ][0];

        Set<Id> expectedProgramIds = new Set<Id>();

        List<ProgramEngagement__c> programEngagements = [SELECT Id, Program__c
            FROM ProgramEngagement__c
            WHERE Contact__c = :con.Id
        ];
        for (ProgramEngagement__c pe : programEngagements) {
            expectedProgramIds.add(pe.Program__c);
        }

        Test.startTest();
        ProgramSelector foo = new ProgramSelector();
        List<Program__c> actual = foo.getProgramsFromProgramEngagements(programEngagements);
        Test.stopTest();

        System.assert(!actual.isEmpty());
        for (Program__c program : actual) {
            System.assert(expectedProgramIds.contains(program.Id));
        }
    }

    public class GetProgramsByContactIdMethod extends Stub.method {
        public Id contactId;
        public List<Program__c> returnValue;

        public GetProgramsByContactIdMethod() {
            super(
                ProgramSelector.class,
                List<Program__c>.class,
                'getProgramsByContactId',
                new List<Stub.Parameter>{ new Stub.Parameter(Id.class, 'contactId') }
            );
        }

        public override Boolean isInstanceOf(Object instance) {
            return instance instanceof ProgramSelector;
        }

        public override List<Object> getExpectedArguments() {
            return new List<Object>{ this.contactId };
        }

        public override Object getReturnValue() {
            return this.returnValue;
        }
    }
}