force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramCohort__c/ProgramCohort__c.object-meta.xml
<CustomObject>
    <label>Program Cohort</label>
    <nameField>
        <label>Program Cohort</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramCohort__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Campaign that this Program Cohort belongs to.</description>
    <inlineHelpText>The Campaign that this Program Cohort belongs to.</inlineHelpText>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Program Cohorts</relationshipLabel>
    <relationshipName>ProgramCohorts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramCohort__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Cohorts</relationshipLabel>
    <relationshipName>ProgramCohorts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProgramCohortService.cls
/*
 *
 *  * Copyright (c) 2021, salesforce.com, inc.
 *  * All rights reserved.
 *  * SPDX-License-Identifier: BSD-3-Clause
 *  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 */

public with sharing class ProgramCohortService {
    @TestVisible
    private CampaignService campaignService = new CampaignService();

    public void createLinkedCampaigns(List<ProgramCohort__c> cohorts) {
        // TODO: bulkify
        Map<Id, Program__c> programById = new Map<Id, Program__c>();
        for (ProgramCohort__c newCohort : cohorts) {
            if (newCohort.Campaign__c == null) {
                programById.put(newCohort.Program__c, null);
            }
        }

        if (!programById.values().isEmpty()) {
            programById = new Map<Id, Program__c>(
                [SELECT Id, Name FROM Program__c WHERE Id = :programById.keySet()]
            );
        }

        for (ProgramCohort__c newCohort : cohorts) {
            if (newCohort.Campaign__c != null) {
                continue;
            }
            String linkedCampaignName =
                programById.get(newCohort.Program__c).Name +
                ': ' +
                newCohort.Name;
            Campaign linkedCampaign = campaignService.createCampaign(
                linkedCampaignName,
                ProgramEngagementService.programEngagementStages
            );
            newCohort.Campaign__c = linkedCampaign.Id;
        }
    }
}