force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/EndDate__c.field-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomField>
    <fullName>EndDate__c</fullName>
    <description>The date the Program is scheduled to end.</description>
    <inlineHelpText>The date the Program is scheduled to end.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>The date the Program is scheduled to start.</description>
    <inlineHelpText>The date the Program is scheduled to start.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the Program. Values are determined by your Admin.</description>
    <inlineHelpText>The status of the Program. Values are determined by your Admin.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProgramCohort__c/ProgramCohort__c.object-meta.xml
<CustomObject>
    <label>Program Cohort</label>
    <nameField>
        <label>Program Cohort</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramCohort__c/fields/EndDate__c.field-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomField>
    <fullName>EndDate__c</fullName>
    <description>The date the Program Cohort is scheduled to end.</description>
    <inlineHelpText>The date the Program Cohort is scheduled to end.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProgramCohort__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Cohorts</relationshipLabel>
    <relationshipName>ProgramCohorts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramCohort__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>The date the Program Cohort is scheduled to start.</description>
    <inlineHelpText>The date the Program Cohort is scheduled to start.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProgramCohort__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the Program Cohort. Values are determined by your Admin.</description>
    <inlineHelpText>The status of the Program Cohort. Values are determined by your Admin.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProgramEngagement__c/ProgramEngagement__c.object-meta.xml
<CustomObject>
    <label>Program Engagement</label>
    <nameField>
        <label>Program Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramEngagement__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Engagements</relationshipLabel>
    <relationshipName>Program_Engagements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramEngagement__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>The date a Contact completes or leaves the Program. If the Program Engagement stage Completed or Withdrawn, the End Date is set to TODAY() by the Process Builder process titled Template: Program Engagement Name. Clone the process template to edit it.</description>
    <inlineHelpText>The date a Contact completes or leaves the Program. If the Program Engagement stage Completed or Withdrawn, the End Date is set to TODAY() by the Process Builder process titled Template: Program Engagement Name. Clone the process template to edit it.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProgramEngagement__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Engagements</relationshipLabel>
    <relationshipName>Program_Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramEngagement__c/fields/ProgramCohort__c.field-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomField>
    <fullName>ProgramCohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Cohort</label>
    <referenceTo>ProgramCohort__c</referenceTo>
    <relationshipLabel>Program Engagements</relationshipLabel>
    <relationshipName>ProgramEngagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramEngagement__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>A Contact&#39;s relationship with the Program Engagement. Values are determined by your Admin.</description>
    <inlineHelpText>A Contact&#39;s relationship with the Program Engagement. Values are determined by your Admin.</inlineHelpText>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProgramEngagement__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>A Contact&#39;s stage in a Program Engagement. Picklist values are determined by your Admin. Don&#39;t delete or modify the API Name of the Active And Enrolled picklist values as they are referenced in PMM reports.</description>
    <inlineHelpText>These Picklist values describe a Contact&#39;s stage of engagement in a Program and are displayed in a Path. Values are determined by your Admin.</inlineHelpText>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Application Denied</fullName>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProgramEngagement__c/fields/StartDate__c.field-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomField>
    <fullName>StartDate__c</fullName>
    <description>If the Program Engagement stage is set to Enrolled or Active, the Start Date is set to TODAY() by the Process Builder process, Template: Program Engagement. Clone the template to edit it.</description>
    <inlineHelpText>If the Program Engagement Stage is Enrolled or Active, the Start Date defaults to today if left blank.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Program__c.field-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/UnitOfMeasurement__c.field-meta.xml
<CustomField>
    <fullName>UnitOfMeasurement__c</fullName>
    <description>The unit used to track the service. For example: hours, meals, sessions, deliveries, kits, etc. Defining a Unit of Measurement standardizes how you measure the delivery of the service.</description>
    <inlineHelpText>The unit used to track the service. For example: hours, meals, sessions, deliveries, kits, etc. Defining a Unit of Measurement standardizes how you measure the delivery of the service.</inlineHelpText>
    <label>Unit of Measurement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/ServiceDelivery__c.object-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomObject>
    <label>Service Delivery</label>
    <nameField>
        <label>Service Delivery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceDelivery__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Deliveries</relationshipLabel>
    <relationshipName>Service_Deliveries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/ProgramEngagement__c.field-meta.xml
<CustomField>
    <fullName>ProgramEngagement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program Engagement</label>
    <referenceTo>ProgramEngagement__c</referenceTo>
    <relationshipLabel>Service Deliveries</relationshipLabel>
    <relationshipName>ServiceDeliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Deliveries</relationshipLabel>
    <relationshipName>ServiceDeliveries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/UnitOfMeasurement__c.field-meta.xml
<CustomField>
    <fullName>UnitOfMeasurement__c</fullName>
    <description>A formula field that displays the UnitOfMeasurement__c field from the Service object.</description>
    <inlineHelpText>A formula field that displays the UnitOfMeasurement field from the Service object.</inlineHelpText>
    <formula>Service__r.UnitOfMeasurement__c</formula>
    <label>Unit of Measurement</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProgramTestDataFactory.cls
/*
 *
 *  * Copyright (c) 2020, salesforce.com, inc.
 *  * All rights reserved.
 *  * SPDX-License-Identifier: BSD-3-Clause
 *  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 */

public with sharing class ProgramTestDataFactory {
    public static void insertTestData(Boolean addServices) {
        Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;

        Contact con1 = new Contact();
        con1.LastName = 'Test Contact';
        con1.AccountId = acc.Id;
        insert con1;

        Contact con2 = new Contact();
        con2.LastName = 'Test Contact';
        con2.AccountId = acc.Id;
        insert con2;

        List<Program__c> programs = new List<Program__c>();
        Program__c program1 = new Program__c();
        program1.Name = 'Program 1';
        program1.Status__c = 'Active';
        program1.StartDate__c = Date.today();
        program1.EndDate__c = Date.today().addDays(30);
        programs.add(program1);

        Program__c program2 = new Program__c();
        program2.Name = 'Program 2';
        program2.Status__c = 'Active';
        program2.StartDate__c = Date.today();
        program2.EndDate__c = Date.today().addDays(90);
        programs.add(program2);

        insert programs;

        List<ProgramCohort__c> programCohorts = new List<ProgramCohort__c>();
        ProgramCohort__c cohort1 = new ProgramCohort__c();
        cohort1.Name = 'Cohort 1';
        cohort1.Program__c = program1.Id;
        cohort1.StartDate__c = System.today();
        cohort1.Status__c = 'Active';
        programCohorts.add(cohort1);

        ProgramCohort__c cohort2 = new ProgramCohort__c();
        cohort2.Name = 'Cohort 2';
        cohort2.Program__c = program2.Id;
        cohort2.StartDate__c = System.today();
        cohort2.Status__c = 'Active';
        programCohorts.add(cohort2);

        insert programCohorts;

        List<ProgramEngagement__c> engagements = new List<ProgramEngagement__c>();

        ProgramEngagement__c engagement1 = new ProgramEngagement__c();
        engagement1.Name = 'Engagement 1';
        engagement1.Stage__c = 'Enrolled';
        engagement1.Contact__c = con1.Id;
        engagement1.Program__c = program1.Id;
        engagement1.Role__c = 'Client';
        engagement1.ProgramCohort__c = cohort1.Id;
        engagements.add(engagement1);

        ProgramEngagement__c engagement2 = new ProgramEngagement__c();
        engagement2.Name = 'Engagement 2';
        engagement2.Stage__c = 'Enrolled';
        engagement2.Contact__c = con1.Id;
        engagement2.Program__c = program2.Id;
        engagement2.Role__c = 'Client';
        engagements.add(engagement2);

        insert engagements;

        if (addServices) {
            List<Service__c> services = new List<Service__c>();

            Service__c service1 = new Service__c();
            service1.Name = 'Service 1';
            service1.Program__c = program1.Id;
            service1.Status__c = 'Active';
            service1.UnitOfMeasurement__c = 'Hours';
            services.add(service1);

            Service__c service2 = new Service__c();
            service2.Name = 'Service 2';
            service2.Program__c = program2.Id;
            service2.Status__c = 'Active';
            service2.UnitOfMeasurement__c = 'Days';
            services.add(service2);

            insert services;

            List<ServiceDelivery__c> serviceDeliveries = new List<ServiceDelivery__c>();

            ServiceDelivery__c serviceDelivery1 = new ServiceDelivery__c();
            serviceDelivery1.ProgramEngagement__c = engagement1.Id;
            serviceDelivery1.Contact__c = con1.Id;
            serviceDelivery1.DeliveryDate__c = System.today();
            serviceDelivery1.Quantity__c = 10;
            serviceDelivery1.Service__c = service1.Id;
            serviceDeliveries.add(serviceDelivery1);

            insert serviceDeliveries;
        }
    }
}