force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramCohort__c/ProgramCohort__c.object-meta.xml
<CustomObject>
    <label>Program Cohort</label>
    <nameField>
        <label>Program Cohort</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramCohort__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Cohorts</relationshipLabel>
    <relationshipName>ProgramCohorts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProgramSelector.cls
public with sharing class ProgramSelector {
    private QueryBuilder queryBuilder = new QueryBuilder();

    public List<ProgramCohort__c> getProgramCohortsByProgramId(Id programId) {
        Set<String> fields = new Set<String>{
            String.valueOf(ProgramCohort__c.Id),
            String.valueOf(ProgramCohort__c.Name)
        };
        return this.getProgramCohortsByProgramId(programId, fields);
    }

    public List<ProgramCohort__c> getProgramCohortsByProgramId(
        Id programId,
        Set<String> fields
    ) {
        if (!Schema.SObjectType.ProgramCohort__c.isAccessible()) {
            return new List<ProgramCohort__c>();
        }

        queryBuilder
            .reset()
            .withSObjectType(ProgramCohort__c.getSObjectType())
            .withSelectFields(new List<String>(fields))
            .addCondition(String.valueOf(ProgramCohort__c.Program__c) + ' = :programId');

        List<ProgramCohort__c> programCohorts = Database.query(
            queryBuilder.buildSoqlQuery()
        );

        return Security.stripInaccessible(AccessType.READABLE, programCohorts)
            .getRecords();
    }
}