force-app/main/default/objects/Contact/fields/ConsecutiveAbsences__c.field-meta.xml
<CustomField>
    <fullName>ConsecutiveAbsences__c</fullName>
    <inlineHelpText>The number of consecutive absences for this Contact, counting back from today. Clears to 0 when most recent Service Delivery was present.</inlineHelpText>
    <label>Consecutive Absences</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/ServiceDelivery__c.object-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomObject>
    <label>Service Delivery</label>
    <nameField>
        <label>Service Delivery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceDelivery__c/fields/AttendanceStatus__c.field-meta.xml
<CustomField>
    <fullName>AttendanceStatus__c</fullName>
    <label>Attendance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Present</fullName>
            </value>
            <value>
                <fullName>Unexcused Absence</fullName>
            </value>
            <value>
                <fullName>Excused Absence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Deliveries</relationshipLabel>
    <relationshipName>Service_Deliveries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/DeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDate__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Delivery Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/Quantity__c.field-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomField>
    <fullName>Quantity__c</fullName>
    <description>A 2-decimal numeric field for Quantity of a Service Delivery expressed in the Unit of Measurement in the Service. For example, 30 minutes of tutoring where the Unit of Measure is hours, Quantity is .50.</description>
    <inlineHelpText>A 2-decimal numeric field for Quantity of a Service Delivery expressed in the Unit of Measurement in the Service. For example, 30 minutes of tutoring where the Unit of Measure is hours, Quantity is .50.</inlineHelpText>
    <label>Quantity</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ContactRollups_SCHED.cls
public class ContactRollups_SCHED implements Database.Batchable<SObject>, Schedulable {
    @TestVisible
    private final static Integer DEFAULT_BATCH_SIZE = 10;

    @TestVisible
    private Integer batchSize {
        get {
            // Allowing for future customization of batch size.
            return DEFAULT_BATCH_SIZE;
        }
        set;
    }

    /*******************************************************************************************************
     * @description Schedulable execute method executes this batch job
     ********************************************************************************************************/
    public void execute(SchedulableContext context) {
        Database.executeBatch(new ContactRollups_SCHED(), batchSize);
    }

    /*******************************************************************************************************
     * @description start Method for the Database.Batchable interface
     * @param bc the BatchableContext
     * @return database.Querylocator
     ********************************************************************************************************/
    public Database.Querylocator start(Database.BatchableContext bc) {
        List<SObjectField> rollupFields = new List<SObjectField>{
            Contact.LastServiceDate__c,
            Contact.ConsecutiveAbsences__c,
            Contact.NumAbsentServiceDeliveries__c,
            Contact.NumPresentServiceDeliveries__c
        };

        String soql = 'SELECT Id FROM Contact WHERE ';

        // Contact with any of our rollup fields populated
        for (SobjectField field : rollupFields) {
            soql += (String.valueOf(field) + ' != null OR ');
        }

        Set<Id> parentIds = new Set<Id>();
        List<ServiceDelivery__c> relevantServiceDeliveries = [
            SELECT Contact__c
            FROM ServiceDelivery__c
            WHERE
                AttendanceStatus__c != NULL
                OR (DeliveryDate__c != NULL
                AND Quantity__c != NULL)
        ];
        for (ServiceDelivery__c child : relevantServiceDeliveries) {
            parentIds.add(child.Contact__c);
        }

        // Contact with any delivery records with attendance
        // Contact with any delivery record with delivery date and qty
        soql += ' Id IN :parentIds';

        return Database.getQueryLocator(soql);
    }

    /*******************************************************************************************************
     * @description execute Method for the Database.Batchable interface
     * @param bc the BatchableContext
     * @param scope the list of Account objects to process
     * @return void
     ********************************************************************************************************/
    public void execute(Database.BatchableContext bc, List<Account> scope) {
        new AttendanceService().doBatchRollups(scope);
    }

    /*******************************************************************************************************
     * @description finish Method for the Database.Batchable interface
     * @param bc the BatchableContext
     * @return void
     ********************************************************************************************************/
    public void finish(Database.BatchableContext bc) {
    }
}