force-app/main/default/objects/Contact/fields/ConsecutiveAbsences__c.field-meta.xml
<CustomField>
    <fullName>ConsecutiveAbsences__c</fullName>
    <inlineHelpText>The number of consecutive absences for this Contact, counting back from today. Clears to 0 when most recent Service Delivery was present.</inlineHelpText>
    <label>Consecutive Absences</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/ServiceDelivery__c.object-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomObject>
    <label>Service Delivery</label>
    <nameField>
        <label>Service Delivery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceDelivery__c/fields/AttendanceStatus__c.field-meta.xml
<CustomField>
    <fullName>AttendanceStatus__c</fullName>
    <label>Attendance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Present</fullName>
            </value>
            <value>
                <fullName>Unexcused Absence</fullName>
            </value>
            <value>
                <fullName>Excused Absence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Deliveries</relationshipLabel>
    <relationshipName>Service_Deliveries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/DeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDate__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Delivery Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/Quantity__c.field-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomField>
    <fullName>Quantity__c</fullName>
    <description>A 2-decimal numeric field for Quantity of a Service Delivery expressed in the Unit of Measurement in the Service. For example, 30 minutes of tutoring where the Unit of Measure is hours, Quantity is .50.</description>
    <inlineHelpText>A 2-decimal numeric field for Quantity of a Service Delivery expressed in the Unit of Measurement in the Service. For example, 30 minutes of tutoring where the Unit of Measure is hours, Quantity is .50.</inlineHelpText>
    <label>Quantity</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ContactRollupsBatchCalc.cls
/*
 *
 *  * Copyright (c) 2021, salesforce.com, inc.
 *  * All rights reserved.
 *  * SPDX-License-Identifier: BSD-3-Clause
 *  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 */

public class ContactRollupsBatchCalc implements Database.Batchable<SObject>, Database.Stateful {
    public ContactRollupsBatchCalc(Set<Id> contactIds) {
        this.contactIds = contactIds;
    }

    @TestVisible
    private Set<Id> contactIds;
    @TestVisible
    private List<String> attendanceStatuses;
    @TestVisible
    private Set<String> presentStatuses;
    @TestVisible
    private Set<String> absentStatuses;
    @TestVisible
    private Map<Id, Contact> contactMap = new Map<Id, Contact>();
    @TestVisible
    private AttendanceSelector attendanceSelector = new AttendanceSelector();
    @TestVisible
    private AttendanceService attendanceService = new AttendanceService();
    @TestVisible
    private SystemAccess systemAccess = new SystemAccess();

    public Database.Querylocator start(Database.BatchableContext bc) {
        presentStatuses = new Set<String>(attendanceService.presentStatuses);
        absentStatuses = new Set<String>(attendanceService.absentStatuses);
        attendanceStatuses = attendanceService.getAttendanceStatuses();

        QueryBuilder query = constructQuery();

        return Database.getQueryLocator(query.buildSoqlQuery());
    }

    public void execute(Database.BatchableContext bc, List<ServiceDelivery__c> scope) {
        processBatch(scope);
    }

    public void finish(Database.BatchableContext bc) {
        //Update the Contacts processed by the last batch
        checkUpdateStatus(contactMap);

        //Remove ids processed in the last batch
        contactIds.removeAll(contactMap.keySet());

        //What remains in contactIds are contacts that need to be reset
        List<Contact> contactsToReset = new List<Contact>();
        for (Id contactId : contactIds) {
            contactsToReset.add(constructNewContact(contactId));
        }
        update contactsToReset;
    }

    private Contact constructNewContact(Id contactId) {
        return new Contact(
            Id = contactId,
            NumAbsentServiceDeliveries__c = 0,
            NumPresentServiceDeliveries__c = 0,
            LastServiceDate__c = null,
            ConsecutiveAbsences__c = 0
        );
    }

    private QueryBuilder constructQuery() {
        QueryBuilder query = new QueryBuilder();
        query.withSObjectType(ServiceDelivery__c.SObjectType);
        query.withSelectFields(
            new List<String>{
                String.valueOf(ServiceDelivery__c.AttendanceStatus__c),
                String.valueOf(ServiceDelivery__c.DeliveryDate__c),
                String.valueOf(ServiceDelivery__c.Contact__c),
                String.valueOf(ServiceDelivery__c.Quantity__c)
            }
        );
        query.addCondition(
            '( ' +
            String.valueOf(ServiceDelivery__c.AttendanceStatus__c) +
            ' IN :attendanceStatuses OR ( ' +
            String.valueOF(ServiceDelivery__c.Quantity__c) +
            ' > 0 AND ' +
            String.valueOf(ServiceDelivery__c.DeliveryDate__c) +
            ' != null )) AND ' +
            String.valueOf(ServiceDelivery__c.Contact__c) +
            ' != null '
        );

        query.withOrderBy(
            String.valueOf(ServiceDelivery__c.Contact__c) +
            ', ' +
            String.valueOf(ServiceDelivery__c.DeliveryDate__c) +
            ' ASC '
        );
        return query;
    }

    //Here we update the contact based on information from the delivery in the iteration
    private Contact processContact(ServiceDelivery__c delivery, Contact thisContact) {
        if (presentStatuses.contains(delivery.AttendanceStatus__c)) {
            thisContact.NumPresentServiceDeliveries__c += 1;
            thisContact.ConsecutiveAbsences__c = 0;
        } else if (absentStatuses.contains(delivery.AttendanceStatus__c)) {
            thisContact.NumAbsentServiceDeliveries__c += 1;
            thisContact.ConsecutiveAbsences__c += 1;
        }
        //Last Service Date
        if (
            (delivery.Quantity__c > 0 && delivery.DeliveryDate__c != null) &&
            (thisContact.LastServiceDate__c == null ||
            delivery.DeliveryDate__c > thisContact.LastServiceDate__c)
        ) {
            thisContact.LastServiceDate__c = delivery.DeliveryDate__c;
        }
        return thisContact;
    }

    //Here we iterate the deliveries that are a part of the batch
    private void processBatch(List<ServiceDelivery__c> deliveries) {
        Set<Id> batchContactIds = new Set<Id>();
        for (ServiceDelivery__c del : deliveries) {
            //Add the contactId to the universe of ids for the batch, we'll need this at the end of the method
            batchContactIds.add(del.Contact__c);
            //Add the contact to the map, if it doesn't exist already
            if (!contactMap.containsKey(del.Contact__c)) {
                contactMap.put(del.Contact__c, constructNewContact(del.Contact__c));
            }

            //Update contact attributes based on current ServiceDelivery__c
            Contact thisContact = contactMap.get(del.Contact__c);
            thisContact = processContact(del, thisContact);
        }
        handleContactUpdates(batchContactIds);
    }

    //Here we find out which contacts have been fully processed and update them
    //If they are no longer in the batch, they are ready to be updated
    private void handleContactUpdates(Set<Id> batchContactIds) {
        List<Contact> contactsToUpdate = new List<Contact>();
        Map<Id, Contact> contactsToUpdateMap = new Map<Id, Contact>();
        for (Contact con : contactMap.values()) {
            if (!batchContactIds.contains(con.Id)) {
                contactsToUpdate.add(con);
                contactsToUpdateMap.put(con.Id, con);
                contactMap.remove(con.Id);
                contactIds.remove(con.Id);
            }
        }
        checkUpdateStatus(contactsToUpdateMap);
    }

    //New method that checks if records need to be updated
    private void checkUpdateStatus(Map<Id, Contact> contacts) {
        List<Contact> contactsToUpdate = new List<Contact>();
        for (Contact con : [
            SELECT
                NumPresentServiceDeliveries__c,
                NumAbsentServiceDeliveries__c,
                LastServiceDate__c,
                ConsecutiveAbsences__c
            FROM Contact
            WHERE Id IN :contacts.keySet()
        ]) {
            Boolean updateContact = false;
            Contact mappedContact = contacts.get(con.Id);

            if (
                con.NumPresentServiceDeliveries__c !=
                mappedContact.NumPresentServiceDeliveries__c
            ) {
                updateContact = true;
            }
            if (
                con.NumAbsentServiceDeliveries__c !=
                mappedContact.NumAbsentServiceDeliveries__c
            ) {
                updateContact = true;
            }
            if (con.LastServiceDate__c != mappedContact.LastServiceDate__c) {
                updateContact = true;
            }
            if (con.ConsecutiveAbsences__c != mappedContact.ConsecutiveAbsences__c) {
                updateContact = true;
            }

            if (updateContact) {
                contactsToUpdate.add(mappedContact);
            }
        }
        systemAccess.updateRecords(contactsToUpdate);
    }
}