force-app/main/default/objects/Contact/fields/ConsecutiveAbsences__c.field-meta.xml
<CustomField>
    <fullName>ConsecutiveAbsences__c</fullName>
    <inlineHelpText>The number of consecutive absences for this Contact, counting back from today. Clears to 0 when most recent Service Delivery was present.</inlineHelpText>
    <label>Consecutive Absences</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/ServiceDelivery__c.object-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomObject>
    <label>Service Delivery</label>
    <nameField>
        <label>Service Delivery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceDelivery__c/fields/AttendanceStatus__c.field-meta.xml
<CustomField>
    <fullName>AttendanceStatus__c</fullName>
    <label>Attendance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Present</fullName>
            </value>
            <value>
                <fullName>Unexcused Absence</fullName>
            </value>
            <value>
                <fullName>Excused Absence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Deliveries</relationshipLabel>
    <relationshipName>Service_Deliveries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/DeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDate__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Delivery Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ServiceDelivery__c/fields/Quantity__c.field-meta.xml
<!--
  ~ /*
  ~  * Copyright (c) 2020, salesforce.com, inc.
  ~  * All rights reserved.
  ~  * SPDX-License-Identifier: BSD-3-Clause
  ~  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
  ~  */
  -->

<CustomField>
    <fullName>Quantity__c</fullName>
    <description>A 2-decimal numeric field for Quantity of a Service Delivery expressed in the Unit of Measurement in the Service. For example, 30 minutes of tutoring where the Unit of Measure is hours, Quantity is .50.</description>
    <inlineHelpText>A 2-decimal numeric field for Quantity of a Service Delivery expressed in the Unit of Measurement in the Service. For example, 30 minutes of tutoring where the Unit of Measure is hours, Quantity is .50.</inlineHelpText>
    <label>Quantity</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ServiceDeliveryRollupsService_TEST.cls
/*
 *
 *  * Copyright (c) 2021, salesforce.com, inc.
 *  * All rights reserved.
 *  * SPDX-License-Identifier: BSD-3-Clause
 *  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 */
@IsTest
public with sharing class ServiceDeliveryRollupsService_TEST {
    private static ServiceDeliveryRollupsService rollupsService = new ServiceDeliveryRollupsService();
    private static TestStub systemAccessStub;
    private static Date yesterday = System.today().addDays(-1);
    private static Id mockContactId = TestUtil.mockId(Contact.SObjectType);
    private static List<String> attendanceStatuses = new ServiceDeliveryService()
        .attendanceStatuses;
    private static List<ServiceDelivery__c> mockDeliveries = new List<ServiceDelivery__c>{
        new ServiceDelivery__c(
            AttendanceStatus__c = 'Present',
            DeliveryDate__c = yesterday,
            Contact__c = mockContactId,
            Quantity__c = 3
        )
    };

    @IsTest
    private static void shouldNotBeInBatchMode() {
        System.assert(
            !rollupsService.isBatchRunning,
            'Should return false when not running in a batch context.'
        );
    }

    @IsTest
    private static void shouldGetDeliveryRollupsQueryFromSystemAccess() {
        String rollupQueryToReturn =
            'SELECT AttendanceStatus__c, DeliveryDate__c, ' +
            String.valueOf(ServiceDelivery__c.Contact__c) +
            ', Quantity__c FROM ' +
            String.valueOf(ServiceDelivery__c.SObjectType);

        systemAccessStub = new StubBuilder(SystemAccess.class)
            .when('getDeliveryRollupsQuery', String.class)
            .calledWith(String.valueOf(ServiceDelivery__c.Contact__c))
            .thenReturn(rollupQueryToReturn)
            .build();

        rollupsService.systemAccess = (SystemAccess) systemAccessStub.create();

        Test.startTest();
        System.assertEquals(
            rollupQueryToReturn,
            rollupsService.getDeliveryRollupsQuery(Contact.SObjectType),
            'Expected the stub to return the query provided.'
        );
        Test.stopTest();

        systemAccessStub.assertCalledAsExpected();
    }

    @IsTest
    private static void shouldRollupDeliveryRecords() {
        Date yesterday = System.today().addDays(-1);

        Test.startTest();
        rollupsService.rollupDeliveryRecords(Contact.SObjectType, mockDeliveries);
        Test.stopTest();

        Set<Id> processedRecords = rollupsService.processedRecordsById.keySet();

        System.assert(
            processedRecords.contains(mockContactId),
            'Expected the contact to have been processed.'
        );
        System.assertEquals(
            1,
            processedRecords.size(),
            'Expected only the one contact provided to be processed.'
        );
    }

    @IsTest
    private static void shouldExitWhenNoDeliveryRecords() {
        Date yesterday = System.today().addDays(-1);

        Test.startTest();
        rollupsService.rollupDeliveryRecords(
            Contact.SObjectType,
            new List<ServiceDelivery__c>()
        );
        Test.stopTest();

        Set<Id> processedRecords = rollupsService.processedRecordsById.keySet();

        System.assert(
            processedRecords.isEmpty(),
            'Expected nothing to be processed when no delivery records are provided.'
        );
    }

    @IsTest
    private static void shouldCommitUpdatedRecords() {
        List<SObject> mockContacts = new List<Contact>{
            new Contact(
                Id = mockContactId,
                LastServiceDate__c = yesterday,
                ConsecutiveAbsences__c = 1,
                NumAbsentServiceDeliveries__c = 1,
                NumPresentServiceDeliveries__c = 1
            )
        };

        List<SObject> expectedContacts = new List<SObject>();
        rollupsService.processedRecordsById.put(
            mockContactId,
            rollupsService.createRollupRecord(mockContactId)
        );
        rollupsService.processedRecordsById.get(mockContactId).absentCount = 0;
        expectedContacts.add(
            rollupsService.processedRecordsById.get(mockContactId).getSObject()
        );
        systemAccessStub = new StubBuilder(SystemAccess.class)
            .when('getRecordsById', SObjectType.class, Set<Id>.class, List<String>.class)
            .calledWith(
                Contact.SObjectType,
                new Set<Id>{ mockContactId },
                rollupsService.buildSelectFieldsForOriginalQuery(Contact.SObjectType)
            )
            .thenReturn(mockContacts)
            .when('updateRecords', List<SObject>.class)
            .calledWith(expectedContacts)
            .thenReturn()
            .build();

        rollupsService.systemAccess = (SystemAccess) systemAccessStub.create();

        Test.startTest();
        rollupsService.commitRollups(Contact.SObjectType);
        Test.stopTest();

        systemAccessStub.assertCalledAsExpected();
    }

    @IsTest
    private static void shouldNotCommitUnchangedRecords() {
        List<SObject> mockContacts = new List<Contact>{
            new Contact(
                Id = mockContactId,
                LastServiceDate__c = null,
                ConsecutiveAbsences__c = null,
                NumAbsentServiceDeliveries__c = 0,
                NumPresentServiceDeliveries__c = null
            )
        };

        List<SObject> expectedContacts = new List<SObject>();
        rollupsService.processedRecordsById.put(
            mockContactId,
            rollupsService.createRollupRecord(mockContactId)
        );
        rollupsService.processedRecordsById.get(mockContactId).absentCount = 0;
        expectedContacts.add(
            rollupsService.processedRecordsById.get(mockContactId).getSObject()
        );

        systemAccessStub = new StubBuilder(SystemAccess.class)
            .when('getRecordsById', SObjectType.class, Set<Id>.class, List<String>.class)
            .calledWith(
                Contact.SObjectType,
                new Set<Id>{ mockContactId },
                rollupsService.buildSelectFieldsForOriginalQuery(Contact.SObjectType)
            )
            .thenReturn(mockContacts)
            .when('updateRecords', List<SObject>.class)
            .calledWith(expectedContacts)
            .expectedNotToBeCalled()
            .build();

        rollupsService.systemAccess = (SystemAccess) systemAccessStub.create();

        Test.startTest();
        rollupsService.commitRollups(Contact.SObjectType);
        Test.stopTest();

        systemAccessStub.assertCalledAsExpected();
    }

    @IsTest
    private static void shouldSetTotalRecordCountWhenBatchIsRunning() {
        systemAccessStub = new StubBuilder(SystemAccess.class)
            .when('getDeliveryRollupsCount', String.class, Id.class)
            .calledWith(String.valueOf(ServiceDelivery__c.Contact__c), mockContactId)
            .thenReturn(5)
            .build();
        rollupsService.systemAccess = (SystemAccess) systemAccessStub.create();
        rollupsService.isBatchRunning = true;

        Test.startTest();
        rollupsService.trackCrossBatchRecordTotals(
            mockDeliveries,
            ServiceDelivery__c.Contact__c
        );
        Test.stopTest();

        System.assertEquals(
            5,
            rollupsService.rollupRecordById.get(mockContactId).totalRecords,
            'Expected the total record count to be set on the contacts rollup record.'
        );

        systemAccessStub.assertCalledAsExpected();
    }

    @IsTest
    private static void shouldNotSetTotalRecordCountWhenBatchIsNotRunning() {
        systemAccessStub = new StubBuilder(SystemAccess.class)
            .when('getDeliveryRollupsCount', String.class, Id.class, List<String>.class)
            .signatureMatches()
            .expectedNotToBeCalled()
            .build();
        rollupsService.systemAccess = (SystemAccess) systemAccessStub.create();
        rollupsService.isBatchRunning = false;

        Test.startTest();
        rollupsService.trackCrossBatchRecordTotals(
            mockDeliveries,
            ServiceDelivery__c.Contact__c
        );
        Test.stopTest();

        systemAccessStub.assertCalledAsExpected();
    }

    @IsTest
    private static void shouldNotResetParentsWhenNoParentsAreProvided() {
        TestStub systemAccessStub = new StubBuilder(SystemAccess.class)
            .when('getParentsHavingDeliveries')
            .signatureMatches()
            .expectedNotToBeCalled()
            .build();

        rollupsService.systemAccess = (SystemAccess) systemAccessStub.create();
        Test.startTest();
        rollupsService.resetParentsWithoutDeliveries(new List<SObject>());
        Test.stopTest();

        systemAccessStub.assertCalledAsExpected();
    }

    @IsTest
    private static void shouldResetParentsWithoutDeliveries() {
        List<SObject> records = new List<SObject>{
            new Contact(Id = TestUtil.mockId(Contact.SObjectType))
        };
        TestStub systemAccessStub = new StubBuilder(SystemAccess.class)
            .when(
                'getParentsHavingDeliveries',
                SObjectType.class,
                String.class,
                List<SObject>.class
            )
            .calledWith(
                Contact.SObjectType,
                String.valueOf(ServiceDelivery__c.Contact__c),
                records
            )
            .thenReturn(new List<SObject>())
            .when('updateRecords', List<SObject>.class)
            .signatureMatches()
            .expectedToBeCalled(1)
            .thenReturn()
            .build();

        rollupsService.systemAccess = (SystemAccess) systemAccessStub.create();
        Test.startTest();
        rollupsService.resetParentsWithoutDeliveries(records);
        Test.stopTest();

        systemAccessStub.assertCalledAsExpected();
    }
}