force-app/main/default/objects/ServiceSession__c/ServiceSession__c.object-meta.xml
<CustomObject>
    <label>Service Session</label>
    <nameField>
        <label>Service Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceSession__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ServiceSessionStatusPicklist.cls
public class ServiceSessionStatusPicklist extends VisualEditor.DynamicPickList {
    private List<Schema.PicklistEntry> statusPicklistEntries = null;

    public override VisualEditor.DataRow getDefaultValue() {
        return new VisualEditor.DataRow('--None--', '');
    }

    public override VisualEditor.DynamicPickListRows getValues() {
        VisualEditor.DynamicPickListRows statusOptions = new VisualEditor.DynamicPickListRows();
        statusOptions.addRow(getDefaultValue());
        List<Schema.PicklistEntry> ples = getStatusPicklistEntries();
        for (Schema.PicklistEntry ple : ples) {
            VisualEditor.DataRow pickListEntryRow = new VisualEditor.DataRow(
                ple.getLabel(),
                ple.getValue()
            );
            statusOptions.addRow(pickListEntryRow);
        }
        return statusOptions;
    }

    private List<Schema.PicklistEntry> getStatusPicklistEntries() {
        if (statusPicklistEntries == null) {
            statusPicklistEntries = ServiceSession__c.Status__c.getDescribe()
                .getPicklistValues();
        }

        return statusPicklistEntries;
    }
}