force-app/main/default/objects/ServiceSession__c/ServiceSession__c.object-meta.xml
<CustomObject>
    <label>Service Session</label>
    <nameField>
        <label>Service Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceSession__c/fields/OmittedContactIds__c.field-meta.xml
<CustomField>
    <fullName>OmittedContactIds__c</fullName>
    <description>This field is used to track which contacts were admitted from the Attendance roster. This is a system field and should not be manually altered.</description>
    <label>Omitted Contact Ids</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ServiceSessionDomain.cls
/*
 *
 *  * Copyright (c) 2022, salesforce.com, inc.
 *  * All rights reserved.
 *  * SPDX-License-Identifier: BSD-3-Clause
 *  * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 */

public with sharing class ServiceSessionDomain {
    public class ServiceSessionDomainException extends Exception {
    }

    public void updateServiceSession(ServiceSession__c serviceSession) {
        String omittedContactIds = serviceSession.OmittedContactIds__c;

        if (
            !PermissionValidator.getInstance()
                .hasObjectAccess(
                    ServiceSession__c.SObjectType,
                    PermissionValidator.CRUDAccessType.UPDATEABLE
                )
        ) {
            throw new ServiceSessionDomainException(Label.UpsertOperationException);
        }

        List<ServiceSession__c> strippedSessions = (List<ServiceSession__c>) Security.stripInaccessible(
                AccessType.UPDATABLE,
                new List<ServiceSession__c>{ serviceSession }
            )
            .getRecords();
        // We are intentionally bypassing security for this system level field
        strippedSessions[0].OmittedContactIds__c = omittedContactIds;

        update strippedSessions;
    }
}